[sourcevunit]
alias = "电压模式"
U = ""
optkeys = ["Vpp", "Vrms", "dBm"]
help = ""
optvalues = ["VPP", "VRMS", "DBM"]
type = "sweep"
cmdheader = "SOURce:VOLTage:UNIT"

[sourcepulsedcyle]
alias = "占空比"
U = ""
optkeys = []
help = ""
optvalues = []
type = "set"
cmdheader = "SOURce:PULSe:DCYCle"

[sourcefreq]
alias = "频率"
U = "Hz"
optkeys = []
help = ""
optvalues = []
type = "sweep"
cmdheader = "SOURce:FREQuency"

[sourcevoffset]
alias = "电压偏移"
U = "V"
optkeys = []
help = ""
optvalues = []
type = "sweep"
cmdheader = "SOURce:VOLTage:OFFSet"

[sourcefunc]
alias = "波形"
U = ""
optkeys = ["sin", "square", "triangle", "ramp", "noise"]
help = ""
optvalues = ["SIN", "SQU", "TRI", "RAMP", "NOIS"]
type = "set"
cmdheader = "SOURce:FUNCtion:SHAPe"

[sourcev]
alias = "电压"
U = "V"
optkeys = []
help = ""
optvalues = []
type = "sweep"
cmdheader = "SOURce:VOLTage"

[conf]
idn = "33120A"
output_labels = []
icon = ""
input_labels = []
cmdtype = "scpi"
