[sourcevunit]
cmdheader = "SOURce:VOLTage:UNIT"
optkeys = ["Vpp", "Vrms", "dBm"]
help = ""
timeoutw = 0.30000001192092896
alias = "电压模式"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = ["VPP", "VRMS", "DBM"]
type = "sweep"

[sourcepulsedcyle]
cmdheader = "SOURce:PULSe:DCYCle"
optkeys = []
help = ""
timeoutw = 0.30000001192092896
alias = "占空比"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "set"

[sourcefreq]
cmdheader = "SOURce:FREQuency"
optkeys = []
help = ""
timeoutw = 0.30000001192092896
alias = "频率"
U = "Hz"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "sweep"

[sourcevoffset]
cmdheader = "SOURce:VOLTage:OFFSet"
optkeys = []
help = ""
timeoutw = 0.30000001192092896
alias = "电压偏移"
U = "V"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "sweep"

[sourcefunc]
cmdheader = "SOURce:FUNCtion:SHAPe"
optkeys = ["sin", "square", "triangle", "ramp", "noise"]
help = ""
timeoutw = 0.30000001192092896
alias = "波形"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = ["SIN", "SQU", "TRI", "RAMP", "NOIS"]
type = "set"

[sourcev]
cmdheader = "SOURce:VOLTage"
optkeys = []
help = ""
timeoutw = 0.30000001192092896
alias = "电压"
U = "V"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "sweep"

[conf]
idn = "33120A"
output_labels = []
icon = ""
input_labels = []
cmdtype = "scpi"
