[querydata]
cmdheader = ""
optkeys = []
help = ""
timeoutw=0.3
alias = "读数据"
U = ""
timeoutr=3
numread = 3
separator = ","
optvalues = []
type = "read"

[conf]
idn = "AH 2500"
output_labels = []
icon = ""
input_labels = []
cmdtype = "scpi"
