[querydata]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3.0
alias = "读数据"
U = ""
timeoutr = 3.0
numread = 3
separator = ","
optvalues = []
type = "read"

[conf]
idn = "AH2500A"
output_labels = []
icon = ""
input_labels = []
cmdtype = "scpi"
