[output]
cmdheader = ":OUTPut:STATe"
optkeys = ["ON", "OFF"]
help = ""
timeoutw = 3
alias = "射频输出"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = ["1", "0"]
type = "set"

[outputmod]
cmdheader = ":OUTPut:MODulation:STATe"
optkeys = ["ON", "OFF"]
help = ""
timeoutw = 3
alias = "调制输出"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = ["1", "0"]
type = "set"

[frequency]
cmdheader = ":SOUR:FREQ"
optkeys = []
help = ""
timeoutw = 3
alias = "频率"
U = "Hz"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "sweep"

[power]
cmdheader = ":SOUR:POW"
optkeys = []
help = ""
timeoutw = 3
alias = "功率"
U = "dBm"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "sweep"

[conf]
idn = "E8254A;E8257D;ESG-3000B;MG3692C"
output_labels = ["RF out"]
icon = ""
input_labels = []
cmdtype = "scpi"
