[channel0]
cmdheader = ""
optkeys = []
help = ""
timeoutw=0.3
alias = "通道1"
U = "V"
timeoutr=3
numread = 1
separator = ""
optvalues = []
type = "sweep"

[channelD]
cmdheader = ""
optkeys = []
help = ""
timeoutw=0.3
alias = "通道14"
U = "V"
timeoutr=3
numread = 1
separator = ""
optvalues = []
type = "sweep"

[channelC]
cmdheader = ""
optkeys = []
help = ""
timeoutw=0.3
alias = "通道13"
U = "V"
timeoutr=3
numread = 1
separator = ""
optvalues = []
type = "sweep"

[channel6]
cmdheader = ""
optkeys = []
help = ""
timeoutw=0.3
alias = "通道7"
U = "V"
timeoutr=3
numread = 1
separator = ""
optvalues = []
type = "sweep"

[channel8]
cmdheader = ""
optkeys = []
help = ""
timeoutw=0.3
alias = "通道9"
U = "V"
timeoutr=3
numread = 1
separator = ""
optvalues = []
type = "sweep"

[channel1]
cmdheader = ""
optkeys = []
help = ""
timeoutw=0.3
alias = "通道2"
U = "V"
timeoutr=3
numread = 1
separator = ""
optvalues = []
type = "sweep"

[channelE]
cmdheader = ""
optkeys = []
help = ""
timeoutw=0.3
alias = "通道15"
U = "V"
timeoutr=3
numread = 1
separator = ""
optvalues = []
type = "sweep"

[channel2]
cmdheader = ""
optkeys = []
help = ""
timeoutw=0.3
alias = "通道3"
U = "V"
timeoutr=3
numread = 1
separator = ""
optvalues = []
type = "sweep"

[channel5]
cmdheader = ""
optkeys = []
help = ""
timeoutw=0.3
alias = "通道6"
U = "V"
timeoutr=3
numread = 1
separator = ""
optvalues = []
type = "sweep"

[channelF]
cmdheader = ""
optkeys = []
help = ""
timeoutw=0.3
alias = "通道16"
U = "V"
timeoutr=3
numread = 1
separator = ""
optvalues = []
type = "sweep"

[channel7]
cmdheader = ""
optkeys = []
help = ""
timeoutw=0.3
alias = "通道8"
U = "V"
timeoutr=3
numread = 1
separator = ""
optvalues = []
type = "sweep"

[channel3]
cmdheader = ""
optkeys = []
help = ""
timeoutw=0.3
alias = "通道4"
U = "V"
timeoutr=3
numread = 1
separator = ""
optvalues = []
type = "sweep"

[channelA]
cmdheader = ""
optkeys = []
help = ""
timeoutw=0.3
alias = "通道11"
U = "V"
timeoutr=3
numread = 1
separator = ""
optvalues = []
type = "sweep"

[channel9]
cmdheader = ""
optkeys = []
help = ""
timeoutw=0.3
alias = "通道10"
U = "V"
timeoutr=3
numread = 1
separator = ""
optvalues = []
type = "sweep"

[channelB]
cmdheader = ""
optkeys = []
help = ""
timeoutw=0.3
alias = "通道12"
U = "V"
timeoutr=3
numread = 1
separator = ""
optvalues = []
type = "sweep"

[channel4]
cmdheader = ""
optkeys = []
help = ""
timeoutw=0.3
alias = "通道5"
U = "V"
timeoutr=3
numread = 1
separator = ""
optvalues = []
type = "sweep"

[conf]
idn = "IKI2102"
output_labels = []
icon = ""
input_labels = []
cmdtype = "scpi"
