[nitrogenlevel]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 0.10000000149011612
alias = "N2液面"
U = ""
timeoutr = 1.0
numread = 1
separator = ""
optvalues = []
type = "read"

[heliumlevel]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 0.10000000149011612
alias = "He4液面"
U = ""
timeoutr = 1.0
numread = 1
separator = ""
optvalues = []
type = "read"

[heliumlevelrmode]
cmdheader = ""
optkeys = ["Fast", "Slow"]
help = ""
timeoutw = 0.10000000149011612
alias = "He4液面读取模式"
U = ""
timeoutr = 1.0
numread = 1
separator = ""
optvalues = ["1", "0"]
type = "set"

[conf]
idn = "ILM200"
output_labels = []
icon = ""
input_labels = []
cmdtype = ""
