[sigrfstz]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 0.30000001192092896
alias = "Z扫描速率"
U = "T/min"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "set"

[drivez]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 0.30000001192092896
alias = "驱动Z"
U = "T"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "set"

[remote]
cmdheader = ""
optkeys = ["Local Locked", "Remote Locked", "Local Unlocked", "Remote Unlocked"]
help = ""
timeoutw = 0.30000001192092896
alias = "远程"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = ["0", "1", "2", "3"]
type = "set"

[zheatertime]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 0.30000001192092896
alias = "Z加热器时间"
U = "s"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "set"

[sigfsetz]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 0.30000001192092896
alias = "Z目标场"
U = "T"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "set"

[sigpfldz]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 0.30000001192092896
alias = "Z当前恒定场"
U = "T"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "read"

[sigpcurz]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 0.30000001192092896
alias = "Z稳恒电流"
U = "A"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "read"

[sigfldz]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 0.30000001192092896
alias = "Z当前场"
U = "T"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "read"

[sigactnz]
cmdheader = ""
optkeys = ["HOLD", "RTOS", "RTOZ", "CLMP"]
help = "HOLD:RTOS:RTOZ:CLMP      Ramp status (Hold, to set, to zero, clamp)"
timeoutw = 0.30000001192092896
alias = "Z状态"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = ["0", "1", "2", "4"]
type = "set"

[zheater]
cmdheader = ""
optkeys = ["OFF", "ON"]
help = ""
timeoutw = 6.0
alias = "Z加热器"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = ["0", "1"]
type = "set"

[conf]
idn = "IPS120"
output_labels = []
icon = ""
input_labels = []
cmdtype = ""

[zheatertimespent]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 0.30000001192092896
alias = "Z加热器触发时间"
U = "s"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "read"
