[cdstep2starttime]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "冷凝阶段2开始时间"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "read"

[sensor1temp]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "道道1温度"
U = "K"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "read"

[cdNVnormal]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "冷凝针阀1"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "set"

[cdstep1starttime]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "冷凝阶段1开始时间"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "read"

[cdtsample]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "冷凝样品腔温度"
U = "K"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "set"

[heaterchannel]
cmdheader = ""
optkeys = ["1", "2", "3"]
help = ""
timeoutw = 3
alias = "加热器通道"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = ["1", "2", "3"]
type = "set"

[cdstep4starttime]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "冷凝阶段4开始时间"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "read"

[cdpidP]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "冷凝PID-P"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "set"

[cdtsorb]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "冷凝Sorb温度"
U = "K"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "set"

[setgasflowctl]
cmdheader = ""
optkeys = ["Manual", "Auto"]
help = ""
timeoutw = 3
alias = "流量控制"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = ["0", "1"]
type = "set"

[cddelay2]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "冷凝阶段2延时"
U = "s"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "set"

[gasflow]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "针阀流量"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "set"

[heaterpct]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "加热器百分比"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "set"

[cdstep]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "冷凝阶段"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "read"

[cdNVcooldown]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "冷凝针阀3"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "set"

[cdpidI]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "冷凝PID-I"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "set"

[sensor3temp]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "道道3温度"
U = "K"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "read"

[pidD]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "PID-D"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "set"

[remote]
cmdheader = ""
optkeys = ["Local Locked", "Remote Locked", "Local Unlocked", "Remote Unlocked"]
help = ""
timeoutw = 3
alias = "远程"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = ["0", "1", "2", "3"]
type = "set"

[pidP]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "PID-P"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "set"

[cddelay3]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "冷凝阶段3延时"
U = "s"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "set"

[cdstep3starttime]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "冷凝阶段3开始时间"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "read"

[cdpidD]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "冷凝PID-D"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "set"

[settemp]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "温度设置"
U = "K"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "set"

[cdstate]
cmdheader = ""
optkeys = ["Condense", "Condensing"]
help = ""
timeoutw = 3
alias = "冷凝状态"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = ["0", "1"]
type = "set"

[cdstep1heater]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "冷凝阶段1加热器"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "set"

[sensor2temp]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "道道2温度"
U = "K"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "read"

[cdNVcondense]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "冷凝针阀2"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "set"

[setheaterctl]
cmdheader = ""
optkeys = ["Manual", "Auto"]
help = ""
timeoutw = 3
alias = "加热器控制"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = ["0", "1"]
type = "set"

[conf]
idn = "ITC503"
output_labels = []
icon = ""
input_labels = []
cmdtype = ""

[pidI]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "PID-I"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "set"
