[sourcefunc]
cmdheader = "smu.source.func"
optkeys = ["CURR", "VOLT"]
help = ""
timeoutw=0.3
alias = "输出模式"
U = ""
timeoutr=3
numread = 1
separator = ""
optvalues = ["smu.FUNC_DC_CURRENT", "smu.FUNC_DC_VOLTAGE"]
type = "set"

[conf]
idn = "MODEL 2450"
output_labels = []
icon = ""
input_labels = []
cmdtype = "tsp"
