[Bmeasureiv]
cmdheader = "smub.measure.iv()"
optkeys = []
help = ""
timeoutw = 3
alias = "B测量电流电压"
U = ""
timeoutr = 3.0
numread = 2
separator = "\t"
optvalues = []
type = "read"

[Bmeasurerangei]
cmdheader = "smub.measure.rangei"
optkeys = ["100nA", "1μA", "10μA", "100μA", "1mA", "10mA", "100mA", "1A", "1.5A"]
help = ""
timeoutw = 3
alias = "B测量电流范围"
U = "A"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = ["1.0e-7", "1.0e-6", "1.0e-5", "0.0001", "0.001", "0.01", "0.1", "1.0", "1.5"]
type = "set"

[Asourcelimitv]
cmdheader = "smua.source.limitv"
optkeys = []
help = ""
timeoutw = 3
alias = "A输出电压限制"
U = "V"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "set"

[Bmeasurerangev]
cmdheader = "smub.measure.rangev"
optkeys = []
help = ""
timeoutw = 3
alias = "B测量电压范围"
U = "V"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "set"

[Ameasurerangei]
cmdheader = "smua.measure.rangei"
optkeys = ["100nA", "1μA", "10μA", "100μA", "1mA", "10mA", "100mA", "1A", "1.5A"]
help = ""
timeoutw = 3
alias = "A测量电流范围"
U = "A"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = ["1.0e-7", "1.0e-6", "1.0e-5", "0.0001", "0.001", "0.01", "0.1", "1.0", "1.5"]
type = "set"

[Ameasureiv]
cmdheader = "smua.measure.iv()"
optkeys = []
help = ""
timeoutw = 3
alias = "A测量电流电压"
U = ""
timeoutr = 3.0
numread = 2
separator = "\t"
optvalues = []
type = "read"

[Asourcerangev]
cmdheader = "smua.source.rangev"
optkeys = ["200mV", "2V", "20V", "200V"]
help = ""
timeoutw = 3
alias = "A输出电压范围"
U = "V"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = ["0.2", "2.0", "20.0", "200.0"]
type = "set"

[Ameasurev]
cmdheader = "smua.measure.v()"
optkeys = []
help = ""
timeoutw = 3
alias = "A测量电压"
U = "V"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "read"

[Bsourcefunc]
cmdheader = "smub.source.func"
optkeys = ["AMP", "VOLT"]
help = ""
timeoutw = 3
alias = "B输出模式"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = ["0.00000e+00", "1.00000e+00"]
type = "set"

[Bmeasurev]
cmdheader = "smub.measure.v()"
optkeys = []
help = ""
timeoutw = 3
alias = "B测量电压"
U = "V"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "read"

[Asourcelimiti]
cmdheader = "smua.source.limiti"
optkeys = []
help = ""
timeoutw = 3
alias = "A输出电流限制"
U = "A"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "set"

[Bsourceleveli]
cmdheader = "smub.source.leveli"
optkeys = []
help = ""
timeoutw = 3
alias = "B输出电流"
U = "A"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "sweep"

[Bsourcelimitv]
cmdheader = "smub.source.limitv"
optkeys = []
help = ""
timeoutw = 3
alias = "B输出电压限制"
U = "V"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "set"

[Bsourcerangev]
cmdheader = "smub.source.rangev"
optkeys = ["200mV", "2V", "20V", "200V"]
help = ""
timeoutw = 3
alias = "B输出电压范围"
U = "V"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = ["0.2", "2.0", "20.0", "200.0"]
type = "set"

[Asourcefunc]
cmdheader = "smua.source.func"
optkeys = ["AMP", "VOLT"]
help = ""
timeoutw = 3
alias = "A输出模式"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = ["0.00000e+00", "1.00000e+00"]
type = "set"

[Boutput]
cmdheader = "smub.source.output"
optkeys = ["ON", "OFF"]
help = ""
timeoutw = 3
alias = "B输出"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = ["1.00000e+00", "0.00000e+00"]
type = "set"

[Asourcerangei]
cmdheader = "smua.source.rangei"
optkeys = ["100nA", "1μA", "10μA", "100μA", "1mA", "10mA", "100mA", "1A", "1.5A"]
help = ""
timeoutw = 3
alias = "A输出电流范围"
U = "A"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = ["1.0e-7", "1.0e-6", "1.0e-5", "0.0001", "0.001", "0.01", "0.1", "1.0", "1.5"]
type = "set"

[Bsourcelevelv]
cmdheader = "smub.source.levelv"
optkeys = []
help = ""
timeoutw = 3
alias = "B输出电压"
U = "V"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "sweep"

[Ameasurei]
cmdheader = "smua.measure.i()"
optkeys = []
help = ""
timeoutw = 3
alias = "A测量电流"
U = "A"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "read"

[Aoutput]
cmdheader = "smua.source.output"
optkeys = ["ON", "OFF"]
help = ""
timeoutw = 3
alias = "A输出"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = ["1.00000e+00", "0.00000e+00"]
type = "set"

[Bmeasurei]
cmdheader = "smub.measure.i()"
optkeys = []
help = ""
timeoutw = 3
alias = "B测量电流"
U = "A"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "read"

[Ameasurerangev]
cmdheader = "smua.measure.rangev"
optkeys = ["200mV", "2V", "20V", "200V"]
help = ""
timeoutw = 3
alias = "A测量电压范围"
U = "V"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = ["0.2", "2.0", "20.0", "200.0"]
type = "set"

[Bsourcelimiti]
cmdheader = "smub.source.limiti"
optkeys = []
help = ""
timeoutw = 3
alias = "B输出电流限制"
U = "A"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "set"

[Bsourcerangei]
cmdheader = "smub.source.rangei"
optkeys = ["100nA", "1μA", "10μA", "100μA", "1mA", "10mA", "100mA", "1A", "1.5A"]
help = ""
timeoutw = 3
alias = "B输出电流范围"
U = "A"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = ["1.0e-7", "1.0e-6", "1.0e-5", "0.0001", "0.001", "0.01", "0.1", "1.0", "1.5"]
type = "set"

[Asourceleveli]
cmdheader = "smua.source.leveli"
optkeys = []
help = ""
timeoutw = 3
alias = "A输出电流"
U = "A"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "sweep"

[conf]
idn = "Model 2612"
output_labels = ["AH", "AHS", "BH", "BHS"]
icon = ""
input_labels = ["AL", "ALS", "BL", "BLS"]
cmdtype = "tsp"

[Asourcelevelv]
cmdheader = "smua.source.levelv"
optkeys = []
help = ""
timeoutw = 3
alias = "A输出电压"
U = "V"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "sweep"
