[Bmeasureiv]
alias = "B测量电流电压"
U = ""
optkeys = []
help = ""
optvalues = []
type = "read"
cmdheader = "smub.measure.iv()"

[Bmeasurerangei]
alias = "B测量电流范围"
U = "A"
optkeys = []
help = ""
optvalues = []
type = "set"
cmdheader = "smub.measure.rangei"

[Asourcelimitv]
alias = "A输出电压限制"
U = "V"
optkeys = []
help = ""
optvalues = []
type = "set"
cmdheader = "smua.source.limitv"

[Bmeasurerangev]
alias = "B测量电压范围"
U = "V"
optkeys = []
help = ""
optvalues = []
type = "set"
cmdheader = "smub.measure.rangev"

[Ameasurerangei]
alias = "A测量电流范围"
U = "A"
optkeys = []
help = ""
optvalues = []
type = "set"
cmdheader = "smua.measure.rangei"

[Ameasureiv]
alias = "A测量电流电压"
U = ""
optkeys = []
help = ""
optvalues = []
type = "read"
cmdheader = "smua.measure.iv()"

[Asourcerangev]
alias = "A输出电压范围"
U = "V"
optkeys = []
help = ""
optvalues = []
type = "set"
cmdheader = "smua.source.rangev"

[Ameasurev]
alias = "A测量电压"
U = "V"
optkeys = []
help = ""
optvalues = []
type = "read"
cmdheader = "smua.measure.v()"

[Bsourcefunc]
alias = "B输出模式"
U = ""
optkeys = ["AMP", "VOLT"]
help = ""
optvalues = ["0.00000e+00", "1.00000e+00"]
type = "set"
cmdheader = "smub.source.func"

[Bmeasurev]
alias = "B测量电压"
U = "V"
optkeys = []
help = ""
optvalues = []
type = "read"
cmdheader = "smub.measure.v()"

[Asourcelimiti]
alias = "A输出电流限制"
U = "A"
optkeys = []
help = ""
optvalues = []
type = "set"
cmdheader = "smua.source.limiti"

[Bsourceleveli]
alias = "B输出电流"
U = "A"
optkeys = []
help = ""
optvalues = []
type = "sweep"
cmdheader = "smub.source.leveli"

[Bsourcelimitv]
alias = "B输出电压限制"
U = "V"
optkeys = []
help = ""
optvalues = []
type = "set"
cmdheader = "smub.source.limitv"

[Bsourcerangev]
alias = "B输出电压范围"
U = "V"
optkeys = []
help = ""
optvalues = []
type = "set"
cmdheader = "smub.source.rangev"

[Asourcefunc]
alias = "A输出模式"
U = ""
optkeys = ["AMP", "VOLT"]
help = ""
optvalues = ["0.00000e+00", "1.00000e+00"]
type = "set"
cmdheader = "smua.source.func"

[Boutput]
alias = "B输出"
U = ""
optkeys = ["ON", "OFF"]
help = ""
optvalues = ["1.00000e+00", "0.00000e+00"]
type = "set"
cmdheader = "smub.source.output"

[Asourcerangei]
alias = "A输出电流范围"
U = "A"
optkeys = []
help = ""
optvalues = []
type = "set"
cmdheader = "smua.source.rangei"

[Bsourcelevelv]
alias = "B输出电压"
U = "V"
optkeys = []
help = ""
optvalues = []
type = "sweep"
cmdheader = "smub.source.levelv"

[Ameasurei]
alias = "A测量电流"
U = "A"
optkeys = []
help = ""
optvalues = []
type = "read"
cmdheader = "smua.measure.i()"

[Aoutput]
alias = "A输出"
U = ""
optkeys = ["ON", "OFF"]
help = ""
optvalues = ["1.00000e+00", "0.00000e+00"]
type = "set"
cmdheader = "smua.source.output"

[Bmeasurei]
alias = "B测量电流"
U = "A"
optkeys = []
help = ""
optvalues = []
type = "read"
cmdheader = "smub.measure.i()"

[Ameasurerangev]
alias = "A测量电压范围"
U = "V"
optkeys = []
help = ""
optvalues = []
type = "set"
cmdheader = "smua.measure.rangev"

[Bsourcelimiti]
alias = "B输出电流限制"
U = "A"
optkeys = []
help = ""
optvalues = []
type = "set"
cmdheader = "smub.source.limiti"

[Bsourcerangei]
alias = "B输出电流范围"
U = "A"
optkeys = []
help = ""
optvalues = []
type = "set"
cmdheader = "smub.source.rangei"

[Asourceleveli]
alias = "A输出电流"
U = "A"
optkeys = []
help = ""
optvalues = []
type = "sweep"
cmdheader = "smua.source.leveli"

[conf]
idn = "Model 2612"
output_labels = ["AH", "AHS", "BH", "BHS"]
icon = ""
input_labels = ["AL", "ALS", "BL", "BLS"]
cmdtype = "tsp"

[Asourcelevelv]
alias = "A输出电压"
U = "V"
optkeys = []
help = ""
optvalues = []
type = "sweep"
cmdheader = "smua.source.levelv"
