[sensedata]
cmdheader = ":SENSE:DATA?"
optkeys = []
help = ""
timeoutw=0.3
alias = "读数据"
U = ""
timeoutr=3
numread = 2
separator = ","
optvalues = []
type = "read"

[deltaarm]
cmdheader = ":DELta:ARM"
optkeys = ["To Be Armed", "Armed", "Not Armed"]
help = ""
timeoutw=0.3
alias = "δ装备"
U = ""
timeoutr=3
numread = 1
separator = ""
optvalues = [" ", "1", "0"]
type = "set"

[output]
cmdheader = ":OUTPut1:STATe"
optkeys = ["ON", "OFF"]
help = ""
timeoutw=0.3
alias = "输出"
U = ""
timeoutr=3
numread = 1
separator = ""
optvalues = ["1", "0"]
type = "set"

[deltahigh]
cmdheader = ":DELta:HIGH"
optkeys = []
help = ""
timeoutw=0.3
alias = "δ高电平"
U = "A"
timeoutr=3
numread = 1
separator = ""
optvalues = []
type = "set"

[deltalow]
cmdheader = ":DELta:LOW"
optkeys = []
help = ""
timeoutw=0.3
alias = "δ低电平"
U = "A"
timeoutr=3
numread = 1
separator = ""
optvalues = []
type = "set"

[conf]
idn = "MODEL 6221"
output_labels = []
icon = ""
input_labels = []
cmdtype = "scpi"
