[inputA]
cmdheader = "KRDG? A"
optkeys = []
help = ""
timeoutw = 0.30000001192092896
alias = "A通道温度"
U = "K"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "read"

[inputB]
cmdheader = "KRDG? B"
optkeys = []
help = ""
timeoutw = 0.30000001192092896
alias = "B通道温度"
U = "K"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "read"

[conf]
idn = "MODEL336;MODEL350"
output_labels = []
icon = ""
input_labels = []
cmdtype = "scpi"
