[coupling]
alias = "耦合"
U = ""
optkeys = ["AC", "DC"]
help = ""
optvalues = ["AC", "DC"]
type = "set"
cmdheader = ":INPut1:COUPling"

[acfrequency]
alias = "交流频率"
U = "Hz"
optkeys = []
help = ""
optvalues = []
type = "sweep"
cmdheader = ":SOURce:FREQuency1:CW"

[ground]
alias = "接地"
U = ""
optkeys = ["FLOAT", "GROUND"]
help = ""
optvalues = ["FLO", "GRO"]
type = "set"
cmdheader = ":INPut1:LOW"

[auxout1]
alias = "附加输出1"
U = "V"
optkeys = []
help = ""
optvalues = []
type = "sweep"
cmdheader = ":SOURce5:VOLTage:LEVel:IMMediate:OFFSet"

[acvoltage]
alias = "交流电压"
U = "V"
optkeys = []
help = ""
optvalues = []
type = "sweep"
cmdheader = ":SOURce:VOLTage:LEVel:IMMediate:AMPLitude"

[slopepPSD]
alias = "衰减率pPSD"
U = ""
optkeys = ["6dB", "12dB", "18dB", "24dB"]
help = ""
optvalues = ["6", "12", "18", "24"]
type = "set"
cmdheader = ":SENSe:FILTer1:LPASs:SLOPe"

[dataout]
alias = "DATA"
U = ""
optkeys = []
help = ""
optvalues = []
type = "read"
cmdheader = "FETCh?"

[sensitivityipPSD]
alias = "电流灵敏度pPSD"
U = "A"
optkeys = []
help = ""
optvalues = []
type = "set"
cmdheader = ":SENSe:CURRent1:AC:RANGe:UPPer"

[auxout2]
alias = "附加输出2"
U = "V"
optkeys = []
help = ""
optvalues = []
type = "sweep"
cmdheader = ":SOURce6:VOLTage:LEVel:IMMediate:OFFSet"

[tconstpPSD]
alias = "时间常数pPSD"
U = "s"
optkeys = []
help = ""
optvalues = []
type = "set"
cmdheader = ":SENSe:FILTer1:LPASs:TCONstant"

[dynres]
alias = "动态储量"
U = ""
optkeys = ["HIGH", "MEDIUM", "LOW"]
help = ""
optvalues = ["HIGH", "MEDium", "LOW"]
type = "set"
cmdheader = ":SENSe:DREServe"

[acphasepPSD]
alias = "交流相位pPSD"
U = "°"
optkeys = []
help = ""
optvalues = []
type = "set"
cmdheader = ":SENSe:PHASe1"

[sensitivityvpPSD]
alias = "电压灵敏度pPSD"
U = "V"
optkeys = []
help = ""
optvalues = []
type = "set"
cmdheader = ":SENSe:VOLTage1:AC:RANGe:UPPer"

[conf]
idn = "LI5650"
output_labels = ["OSC OUT", "REF OUT"]
icon = ""
input_labels = ["I", "A", "B", "REF IN"]
cmdtype = "scpi"
