[tconst]
alias = "时间常数"
U = ""
numread = 1
optkeys = ["10μs", "30μs", "100μs", "300μs", "1ms", "3ms", "10ms", "30ms", "100ms", "300ms", "1s", "3s", "10s", "30s", "100s", "300s", "1ks", "3ks", "10ks", "30ks"]
separator = ""
optvalues = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19"]
help = ""
type = "set"
cmdheader = "TCON"

[coupling]
alias = "耦合"
U = ""
numread = 1
optkeys = ["AC", "DC"]
separator = ""
optvalues = ["0", "1"]
help = ""
type = "set"
cmdheader = "ICPL"

[acvoltagerangeCtrl]
alias = "交流电压范围Ctrl"
U = ""
numread = 1
optkeys = ["50mV", "500mV", "5V"]
separator = ""
optvalues = ["0", "1", "2"]
help = ""
type = "set"
cmdheader = ""

[acfrequency]
alias = "交流频率"
U = "Hz"
numread = 1
optkeys = []
separator = ""
optvalues = []
help = ""
type = "sweep"
cmdheader = "FREQ"

[sensitivityv]
alias = "电压灵敏度"
U = ""
numread = 1
optkeys = ["2nV", "5nV", "10nV", "20nV", "50nV", "100nV", "200nV", "500nV", "1μV", "2μV", "5μV", "10μV", "20μV", "50μV", "100μV", "200μV", "500μV", "1mV", "2mV", "5mV", "10mV", "20mV", "50mV", "100mV", "200mV", "500mV", "1V"]
separator = ""
optvalues = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26"]
help = ""
type = "set"
cmdheader = "VSEN"

[acvoltageCtrl]
alias = "交流电压Ctrl"
U = "V"
numread = 1
optkeys = []
separator = ""
optvalues = []
help = ""
type = "sweep"
cmdheader = ""

[ground]
alias = "接地"
U = ""
numread = 1
optkeys = ["FLOAT", "GROUND"]
separator = ""
optvalues = ["0", "1"]
help = ""
type = "set"
cmdheader = "IGND"

[auxout1]
alias = "附加输出1"
U = "V"
numread = 1
optkeys = []
separator = ""
optvalues = []
help = ""
type = "sweep"
cmdheader = "AUXV 1"

[sensitivityi]
alias = "电流灵敏度"
U = ""
numread = 1
optkeys = ["5fA", "10fA", "20fA", "50fA", "100fA", "200fA", "500fA", "1pA", "2pA", "5pA", "10pA", "20pA", "50pA", "100pA", "200pA", "500pA", "1nA", "2nA", "5nA", "10nA", "20nA", "50nA", "100nA", "200nA", "500nA", "1μA"]
separator = ""
optvalues = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26"]
help = ""
type = "set"
cmdheader = "ISEN"

[acvoltage]
alias = "交流电压"
U = ""
numread = 1
optkeys = []
separator = ""
optvalues = []
help = ""
type = "set"
cmdheader = "AMPL"

[slope]
alias = "衰减率"
U = ""
numread = 1
optkeys = ["6dB", "12dB", "18dB", "24dB"]
separator = ""
optvalues = ["0", "1", "2", "3"]
help = ""
type = "set"
cmdheader = "SLOP"

[dataout]
alias = "DATA"
U = ""
numread = 2
optkeys = []
separator = ","
optvalues = []
help = ""
type = "read"
cmdheader = "DOUT?"

[auxout2]
alias = "附加输出2"
U = "V"
numread = 1
optkeys = []
separator = ""
optvalues = []
help = ""
type = "sweep"
cmdheader = "AUXV 2"

[dynres]
alias = "动态储量"
U = ""
numread = 1
optkeys = ["HIGH", "MEDIUM", "LOW"]
separator = ""
optvalues = ["0", "1", "2"]
help = ""
type = "set"
cmdheader = "DRSV"

[phase]
alias = "交流相位"
U = "°"
numread = 1
optkeys = []
separator = ""
optvalues = []
help = ""
type = "sweep"
cmdheader = "PHAS"

[conf]
idn = "LI5640"
output_labels = ["OSC OUT", "REF OUT"]
icon = ""
input_labels = ["I", "A", "B", "REF IN"]
cmdtype = "scpi"
