[coupling]
cmdheader = ":INPut1:COUPling"
optkeys = ["AC", "DC"]
help = ""
timeoutw = 0.10000000149011612
alias = "耦合"
U = ""
timeoutr = 1.0
numread = 1
separator = ""
optvalues = ["AC", "DC"]
type = "set"

[acvoltagerange]
cmdheader = ":SOURce:VOLTage:RANGe"
optkeys = ["10mV", "100mV", "1V"]
help = ""
timeoutw = 0.10000000149011612
alias = "交流电压范围"
U = "V"
timeoutr = 1.0
numread = 1
separator = ""
optvalues = ["0.01", "0.1", "1.0"]
type = "set"

[acfrequency]
cmdheader = ":SENSe:FREQuency1?"
optkeys = []
help = ""
timeoutw = 0.10000000149011612
alias = "交流频率"
U = "Hz"
timeoutr = 1.0
numread = 1
separator = ""
optvalues = []
type = "read"

[ground]
cmdheader = ":INPut1:LOW"
optkeys = ["FLOAT", "GROUND"]
help = ""
timeoutw = 0.10000000149011612
alias = "接地"
U = ""
timeoutr = 1.0
numread = 1
separator = ""
optvalues = ["FLO", "GRO"]
type = "set"

[auxout1]
cmdheader = ":SOURce5:VOLTage:LEVel:IMMediate:OFFSet"
optkeys = []
help = ""
timeoutw = 0.10000000149011612
alias = "附加输出1"
U = "V"
timeoutr = 1.0
numread = 1
separator = ""
optvalues = []
type = "sweep"

[acvoltage]
cmdheader = ":SOURce:VOLTage:LEVel:IMMediate:AMPLitude"
optkeys = []
help = ""
timeoutw = 0.10000000149011612
alias = "交流电压"
U = "V"
timeoutr = 1.0
numread = 1
separator = ""
optvalues = []
type = "sweep"

[oscfrequency]
cmdheader = ":SOURce:FREQuency1:CW"
optkeys = []
help = ""
timeoutw = 0.10000000149011612
alias = "OSC交流频率"
U = "Hz"
timeoutr = 1.0
numread = 1
separator = ""
optvalues = []
type = "sweep"

[slopepPSD]
cmdheader = ":SENSe:FILTer1:LPASs:SLOPe"
optkeys = ["6dB", "12dB", "18dB", "24dB"]
help = ""
timeoutw = 0.10000000149011612
alias = "衰减率pPSD"
U = ""
timeoutr = 1.0
numread = 1
separator = ""
optvalues = ["6", "12", "18", "24"]
type = "set"

[dataout]
cmdheader = "FETCh?"
optkeys = []
help = ""
timeoutw = 0.10000000149011612
alias = "DATA"
U = ""
timeoutr = 1.0
numread = 2
separator = ","
optvalues = []
type = "read"

[sensitivityipPSD]
cmdheader = ":SENSe:CURRent1:AC:RANGe:UPPer"
optkeys = ["10fA", "20fA", "50fA", "100fA", "200fA", "500fA", "1pA", "2pA", "5pA", "10pA", "20pA", "50pA", "100pA", "200pA", "500pA", "1nA", "2nA", "5nA", "10nA", "20nA", "50nA", "100nA", "200nA", "500nA", "1μA"]
help = ""
timeoutw = 0.10000000149011612
alias = "电流灵敏度pPSD"
U = "A"
timeoutr = 1.0
numread = 1
separator = ""
optvalues = ["1e-14", "2e-14", "5e-14", "1.0e-13", "2.0e-13", "5.0e-13", "1.0e-12", "2.0e-12", "5.0e-12", "1.0e-11", "2.0e-11", "5.0e-11", "1.0e-10", "2.0e-10", "5.0e-10", "1.0e-9", "2.0e-9", "5.0e-9", "1.0e-8", "2.0e-8", "5.0e-8", "1.0e-7", "2.0e-7", "5.0e-7", "1.0e-6"]
type = "set"

[auxout2]
cmdheader = ":SOURce6:VOLTage:LEVel:IMMediate:OFFSet"
optkeys = []
help = ""
timeoutw = 0.10000000149011612
alias = "附加输出2"
U = "V"
timeoutr = 1.0
numread = 1
separator = ""
optvalues = []
type = "sweep"

[tconstpPSD]
cmdheader = ":SENSe:FILTer1:LPASs:TCONstant"
optkeys = ["5μs", "10μs", "20μs", "50μs", "100μs", "200μs", "500μs", "1ms", "2ms", "5ms", "10ms", "20ms", "50ms", "100ms", "200ms", "500ms", "1s", "2s", "5s", "10s", "20s", "50s", "100s", "200s", "500s", "1ks", "2ks", "5ks", "10ks", "20ks", "50ks"]
help = ""
timeoutw = 0.10000000149011612
alias = "时间常数pPSD"
U = "s"
timeoutr = 1.0
numread = 1
separator = ""
optvalues = ["5.0e-6", "1.0e-5", "2.0e-5", "5.0e-5", "0.0001", "0.0002", "0.0005", "0.001", "0.002", "0.005", "0.01", "0.02", "0.05", "0.1", "0.2", "0.5", "1.0", "2.0", "5.0", "10.0", "20.0", "50.0", "100.0", "200.0", "500.0", "1000.0", "2000.0", "5000.0", "10000.0", "20000.0", "50000.0"]
type = "set"

[dynres]
cmdheader = ":SENSe:DREServe"
optkeys = ["HIGH", "MED", "LOW"]
help = ""
timeoutw = 0.10000000149011612
alias = "动态储量"
U = ""
timeoutr = 1.0
numread = 1
separator = ""
optvalues = ["HIGH", "MED", "LOW"]
type = "set"

[acphasepPSD]
cmdheader = ":SENSe:PHASe1"
optkeys = []
help = ""
timeoutw = 0.10000000149011612
alias = "交流相位pPSD"
U = "°"
timeoutr = 1.0
numread = 1
separator = ""
optvalues = []
type = "sweep"

[sensitivityvpPSD]
cmdheader = ":SENSe:VOLTage1:AC:RANGe:UPPer"
optkeys = ["10nV", "20nV", "50nV", "100nV", "200nV", "500nV", "1μV", "2μV", "5μV", "10μV", "20μV", "50μV", "100μV", "200μV", "500μV", "1mV", "2mV", "5mV", "10mV", "20mV", "50mV", "100mV", "200mV", "500mV", "1V"]
help = ""
timeoutw = 0.10000000149011612
alias = "电压灵敏度pPSD"
U = "V"
timeoutr = 1.0
numread = 1
separator = ""
optvalues = ["1.0e-8", "2.0e-8", "5.0e-8", "1.0e-7", "2.0e-7", "5.0e-7", "1.0e-6", "2.0e-6", "5.0e-6", "1.0e-5", "2.0e-5", "5.0e-5", "0.0001", "0.0002", "0.0005", "0.001", "0.002", "0.005", "0.01", "0.02", "0.05", "0.1", "0.2", "0.5", "1.0"]
type = "set"

[conf]
idn = "LI5650"
output_labels = ["OSC OUT", "REF OUT"]
icon = ""
input_labels = ["I", "A", "B", "REF IN"]
cmdtype = "scpi"
