[coupling]
alias = "耦合"
U = ""
optkeys = ["AC", "DC"]
help = ""
optvalues = ["AC", "DC"]
type = "set"
cmdheader = ":INPut1:COUPling"

[acvoltagerange]
alias = "交流电压范围"
U = "V"
optkeys = []
help = ""
optvalues = []
type = "set"
cmdheader = ":SOURce:VOLTage:RANGe"

[acfrequency]
alias = "交流频率"
U = "Hz"
optkeys = []
help = ""
optvalues = []
type = "sweep"
cmdheader = ":SOURce:FREQuency1:CW"

[dataoutCtrl]
alias = "DATA-Ctrl"
U = ""
optkeys = []
help = ""
optvalues = []
type = "read"
cmdheader = ""

[ground]
alias = "接地"
U = ""
optkeys = ["FLOAT", "GROUND"]
help = ""
optvalues = ["FLO", "GRO"]
type = "set"
cmdheader = ":INPut1:LOW"

[auxout1]
alias = "附加输出1"
U = "V"
optkeys = []
help = ""
optvalues = []
type = "sweep"
cmdheader = ":SOURce5:VOLTage:LEVel:IMMediate:OFFSet"

[acvoltage]
alias = "交流电压"
U = "V"
optkeys = []
help = ""
optvalues = []
type = "sweep"
cmdheader = ":SOURce:VOLTage:LEVel:IMMediate:AMPLitude"

[slopepPSD]
alias = "衰减率pPSD"
U = ""
optkeys = ["6dB", "12dB", "18dB", "24dB"]
help = ""
optvalues = ["6", "12", "18", "24"]
type = "set"
cmdheader = ":SENSe:FILTer1:LPASs:SLOPe"

[dataout]
alias = "DATA"
U = ""
optkeys = []
help = ""
optvalues = []
type = "read"
cmdheader = "FETCh?"

[sensitivityipPSD]
alias = "电流灵敏度pPSD"
U = "A"
optkeys = ["10fA", "20fA", "50fA", "100fA", "200fA", "500fA", "1pA", "2pA", "5pA", "10pA", "20pA", "50pA", "100pA", "200pA", "500pA", "1nA", "2nA", "5nA", "10nA", "20nA", "50nA", "100nA", "200nA", "500nA", "1μA"]
help = ""
optvalues = ["1e-14", "2e-14", "5e-14", "1e-13", "2e-13", "5e-13", "1e-12", "2e-12", "5e-12", "1e-11", "2e-11", "5e-11", "1e-10", "2e-10", "5e-10", "1e-9", "2e-9", "5e-9", "1e-8", "2e-8", "5e-8", "1e-7", "2e-7", "5e-7", "1e-6"]
type = "set"
cmdheader = ":SENSe:CURRent1:AC:RANGe:UPPer"

[auxout2]
alias = "附加输出2"
U = "V"
optkeys = []
help = ""
optvalues = []
type = "sweep"
cmdheader = ":SOURce6:VOLTage:LEVel:IMMediate:OFFSet"

[tconstpPSD]
alias = "时间常数pPSD"
U = "s"
optkeys = ["5μs", "10μs", "20μs", "50μs", "100μs", "200μs", "500μs", "1ms", "2ms", "5ms", "10ms", "20ms", "50ms", "100ms", "200ms", "500ms", "1s", "2s", "5s", "10s", "20s", "50s", "100s", "200s", "500s", "1ks", "2ks", "5ks", "10ks", "20ks", "50ks"]
help = ""
optvalues = ["5e-6", "1e-5", "2e-5", "5e-5", "1e-4", "2e-4", "5e-4", "0.001", "0.002", "0.005", "0.01", "0.02", "0.05", "0.1", "0.2", "0.5", "1", "2", "5", "10", "20", "50", "100", "200", "500", "1000", "2000", "5000", "1e4", "2e4", "5e4"]
type = "set"
cmdheader = ":SENSe:FILTer1:LPASs:TCONstant"

[dynres]
alias = "动态储量"
U = ""
optkeys = ["HIGH", "MEDIUM", "LOW"]
help = ""
optvalues = ["HIGH", "MEDium", "LOW"]
type = "set"
cmdheader = ":SENSe:DREServe"

[acphasepPSD]
alias = "交流相位pPSD"
U = "°"
optkeys = []
help = ""
optvalues = []
type = "set"
cmdheader = ":SENSe:PHASe1"

[sensitivityvpPSD]
alias = "电压灵敏度pPSD"
U = "V"
optkeys = ["10nV", "20nV", "50nV", "100nV", "200nV", "500nV", "1μV", "2μV", "5μV", "10μV", "20μV", "50μV", "100μV", "200μV", "500μV", "1mV", "2mV", "5mV", "10mV", "20mV", "50mV", "100mV", "200mV", "500mV", "1V"]
help = ""
optvalues = ["1.0e-8", "2.0e-8", "5.0e-8", "1.0e-7", "2.0e-7", "5.0e-7", "1.0e-6", "2.0e-6", "5.0e-6", "1.0e-5", "2.0e-5", "5.0e-5", "1.0e-4", "2.0e-4", "5.0e-4", "0.001", "0.002", "0.005", "0.01", "0.02", "0.05", "0.1", "0.2", "0.5", "1"]
type = "set"
cmdheader = ":SENSe:VOLTage1:AC:RANGe:UPPer"

[conf]
idn = "LI5650"
output_labels = ["OSC OUT", "REF OUT"]
icon = ""
input_labels = ["I", "A", "B", "REF IN"]
cmdtype = "scpi"
