[tconst]
cmdheader = "TCON"
optkeys = ["10μs", "30μs", "100μs", "300μs", "1ms", "3ms", "10ms", "30ms", "100ms", "300ms", "1s", "3s", "10s", "30s", "100s", "300s", "1ks", "3ks", "10ks", "30ks"]
help = ""
timeoutw = 0.30000001192092896
alias = "时间常数"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19"]
type = "set"

[coupling]
cmdheader = "ICPL"
optkeys = ["AC", "DC"]
help = ""
timeoutw = 0.30000001192092896
alias = "耦合"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = ["0", "1"]
type = "set"

[acvoltagerangeCtrl]
cmdheader = ""
optkeys = ["50mV", "500mV", "5V"]
help = ""
timeoutw = 0.30000001192092896
alias = "交流电压范围Ctrl"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = ["0", "1", "2"]
type = "set"

[acfrequency]
cmdheader = "FREQ"
optkeys = []
help = ""
timeoutw = 0.30000001192092896
alias = "交流频率"
U = "Hz"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "sweep"

[sensitivityv]
cmdheader = "VSEN"
optkeys = ["2nV", "5nV", "10nV", "20nV", "50nV", "100nV", "200nV", "500nV", "1μV", "2μV", "5μV", "10μV", "20μV", "50μV", "100μV", "200μV", "500μV", "1mV", "2mV", "5mV", "10mV", "20mV", "50mV", "100mV", "200mV", "500mV", "1V"]
help = ""
timeoutw = 0.30000001192092896
alias = "电压灵敏度"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26"]
type = "set"

[acvoltageCtrl]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 0.30000001192092896
alias = "交流电压Ctrl"
U = "V"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "sweep"

[ground]
cmdheader = "IGND"
optkeys = ["FLOAT", "GROUND"]
help = ""
timeoutw = 0.30000001192092896
alias = "接地"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = ["0", "1"]
type = "set"

[auxout1]
cmdheader = "AUXV 1"
optkeys = []
help = ""
timeoutw = 0.30000001192092896
alias = "附加输出1"
U = "V"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "sweep"

[sensitivityi]
cmdheader = "ISEN"
optkeys = ["5fA", "10fA", "20fA", "50fA", "100fA", "200fA", "500fA", "1pA", "2pA", "5pA", "10pA", "20pA", "50pA", "100pA", "200pA", "500pA", "1nA", "2nA", "5nA", "10nA", "20nA", "50nA", "100nA", "200nA", "500nA", "1μA"]
help = ""
timeoutw = 0.30000001192092896
alias = "电流灵敏度"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26"]
type = "set"

[acvoltage]
cmdheader = "AMPL"
optkeys = []
help = ""
timeoutw = 0.30000001192092896
alias = "交流电压"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "set"

[slope]
cmdheader = "SLOP"
optkeys = ["6dB", "12dB", "18dB", "24dB"]
help = ""
timeoutw = 0.30000001192092896
alias = "衰减率"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = ["0", "1", "2", "3"]
type = "set"

[dataout]
cmdheader = "DOUT?"
optkeys = []
help = ""
timeoutw = 0.30000001192092896
alias = "DATA"
U = ""
timeoutr = 3.0
numread = 2
separator = ","
optvalues = []
type = "read"

[auxout2]
cmdheader = "AUXV 2"
optkeys = []
help = ""
timeoutw = 0.30000001192092896
alias = "附加输出2"
U = "V"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "sweep"

[dynres]
cmdheader = "DRSV"
optkeys = ["HIGH", "MEDIUM", "LOW"]
help = ""
timeoutw = 0.30000001192092896
alias = "动态储量"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = ["0", "1", "2"]
type = "set"

[phase]
cmdheader = "PHAS"
optkeys = []
help = ""
timeoutw = 0.30000001192092896
alias = "交流相位"
U = "°"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "sweep"

[conf]
idn = "LI5640"
output_labels = ["OSC OUT", "REF OUT"]
icon = ""
input_labels = ["I", "A", "B", "REF IN"]
cmdtype = "scpi"
