[sigactny]
alias = "Y状态"
U = ""
optkeys = ["HOLD", "RTOS", "RTOZ", "CLMP"]
help = "HOLD:RTOS:RTOZ:CLMP      Ramp status (Hold, to set, to zero, clamp)"
optvalues = ["HOLD", "RTOS", "RTOZ", "CLMP"]
type = "set"
cmdheader = ""

[sigfldy]
alias = "Y当前场"
U = "T"
optkeys = []
help = ""
optvalues = []
type = "read"
cmdheader = ""

[sigrfstz]
alias = "Z扫描速率"
U = "T/min"
optkeys = []
help = ""
optvalues = []
type = "set"
cmdheader = ""

[sigfsetx]
alias = "X目标场"
U = "T"
optkeys = []
help = ""
optvalues = []
type = "set"
cmdheader = ""

[sigfldx]
alias = "X当前场"
U = "T"
optkeys = []
help = ""
optvalues = []
type = "read"
cmdheader = ""

[sigrfsty]
alias = "Y扫描速率"
U = "T/min"
optkeys = []
help = ""
optvalues = []
type = "set"
cmdheader = ""

[sigactnx]
alias = "X状态"
U = ""
optkeys = ["HOLD", "RTOS", "RTOZ", "CLMP"]
help = "HOLD:RTOS:RTOZ:CLMP      Ramp status (Hold, to set, to zero, clamp)"
optvalues = ["HOLD", "RTOS", "RTOZ", "CLMP"]
type = "set"
cmdheader = ""

[sigpfldy]
alias = "Y当前恒定场"
U = "T"
optkeys = []
help = ""
optvalues = []
type = "read"
cmdheader = ""

[sigfsetz]
alias = "Z目标场"
U = "T"
optkeys = []
help = ""
optvalues = []
type = "set"
cmdheader = ""

[sigrfstx]
alias = "X扫描速率"
U = "T/min"
optkeys = []
help = ""
optvalues = []
type = "set"
cmdheader = ""

[sigpfldz]
alias = "Z当前恒定场"
U = "T"
optkeys = []
help = ""
optvalues = []
type = "read"
cmdheader = ""

[sigpfldx]
alias = "X当前恒定场"
U = "T"
optkeys = []
help = ""
optvalues = []
type = "read"
cmdheader = ""

[sigfldz]
alias = "Z当前场"
U = "T"
optkeys = []
help = ""
optvalues = []
type = "read"
cmdheader = ""

[sigactnz]
alias = "Z状态"
U = ""
optkeys = ["HOLD", "RTOS", "RTOZ", "CLMP"]
help = "HOLD:RTOS:RTOZ:CLMP      Ramp status (Hold, to set, to zero, clamp)"
optvalues = ["HOLD", "RTOS", "RTOZ", "CLMP"]
type = "set"
cmdheader = ""

[zheater]
alias = "Z加热器"
U = ""
optkeys = ["ON", "OFF"]
help = ""
optvalues = ["ON", "OFF"]
type = "set"
cmdheader = ""

[conf]
idn = "MERCURY IPS"
output_labels = ["X -", "Y -", "Z -"]
icon = ""
input_labels = ["X +", "Y +", "Z +"]
cmdtype = "scpi"

[sigfsety]
alias = "Y目标场"
U = "T"
optkeys = []
help = ""
optvalues = []
type = "set"
cmdheader = ""
