[sigactny]
alias = "Y状态"
U = ""
numread = 1
optkeys = ["HOLD", "RTOS", "RTOZ", "CLMP"]
separator = ""
optvalues = ["HOLD", "RTOS", "RTOZ", "CLMP"]
help = "HOLD:RTOS:RTOZ:CLMP      Ramp status (Hold, to set, to zero, clamp)"
type = "set"
cmdheader = ""

[magnetT]
alias = "磁体温度"
U = "K"
numread = 1
optkeys = []
separator = ""
optvalues = []
help = "magnet temperature"
type = "read"
cmdheader = ""

[nitrogenlevel]
alias = "N2液面"
U = ""
numread = 1
optkeys = []
separator = ""
optvalues = []
help = ""
type = "read"
cmdheader = ""

[heliumlevel]
alias = "He4液面"
U = ""
numread = 1
optkeys = []
separator = ""
optvalues = []
help = ""
type = "read"
cmdheader = ""

[sigvoltz]
alias = "Z电压"
U = "V"
numread = 1
optkeys = []
separator = ""
optvalues = []
help = ""
type = "read"
cmdheader = ""

[sigfldy]
alias = "Y当前场"
U = "T"
numread = 1
optkeys = []
separator = ""
optvalues = []
help = ""
type = "read"
cmdheader = ""

[sigrfstz]
alias = "Z扫描速率"
U = "T/min"
numread = 1
optkeys = []
separator = ""
optvalues = []
help = ""
type = "set"
cmdheader = ""

[sigfsetx]
alias = "X目标场"
U = "T"
numread = 1
optkeys = []
separator = ""
optvalues = []
help = ""
type = "set"
cmdheader = ""

[sigfldx]
alias = "X当前场"
U = "T"
numread = 1
optkeys = []
separator = ""
optvalues = []
help = ""
type = "read"
cmdheader = ""

[heliumlevelrmode]
alias = "He4液面读取模式"
U = ""
numread = 1
optkeys = ["Fast", "Slow"]
separator = ""
optvalues = ["OFF", "ON"]
help = ""
type = "set"
cmdheader = ""

[sigrfsty]
alias = "Y扫描速率"
U = "T/min"
numread = 1
optkeys = []
separator = ""
optvalues = []
help = ""
type = "set"
cmdheader = ""

[drivez]
alias = "驱动Z"
U = "T"
numread = 1
optkeys = []
separator = ""
optvalues = []
help = ""
type = "set"
cmdheader = ""

[sigcurrz]
alias = "Z电流"
U = "A"
numread = 1
optkeys = []
separator = ""
optvalues = []
help = ""
type = "read"
cmdheader = ""

[drivex]
alias = "驱动X"
U = "T"
numread = 1
optkeys = []
separator = ""
optvalues = []
help = ""
type = "set"
cmdheader = ""

[sigactnx]
alias = "X状态"
U = ""
numread = 1
optkeys = ["HOLD", "RTOS", "RTOZ", "CLMP"]
separator = ""
optvalues = ["HOLD", "RTOS", "RTOZ", "CLMP"]
help = "HOLD:RTOS:RTOZ:CLMP      Ramp status (Hold, to set, to zero, clamp)"
type = "set"
cmdheader = ""

[sigpfldy]
alias = "Y当前恒定场"
U = "T"
numread = 1
optkeys = []
separator = ""
optvalues = []
help = ""
type = "read"
cmdheader = ""

[zheatertime]
alias = "Z加热器时间"
U = "s"
numread = 1
optkeys = []
separator = ""
optvalues = []
help = ""
type = "set"
cmdheader = ""

[sigfsetz]
alias = "Z目标场"
U = "T"
numread = 1
optkeys = []
separator = ""
optvalues = []
help = ""
type = "set"
cmdheader = ""

[sigrfstx]
alias = "X扫描速率"
U = "T/min"
numread = 1
optkeys = []
separator = ""
optvalues = []
help = ""
type = "set"
cmdheader = ""

[sigpfldz]
alias = "Z当前恒定场"
U = "T"
numread = 1
optkeys = []
separator = ""
optvalues = []
help = ""
type = "read"
cmdheader = ""

[sigpcurz]
alias = "Z稳恒电流"
U = "A"
numread = 1
optkeys = []
separator = ""
optvalues = []
help = ""
type = "read"
cmdheader = ""

[sigpfldx]
alias = "X当前恒定场"
U = "T"
numread = 1
optkeys = []
separator = ""
optvalues = []
help = ""
type = "read"
cmdheader = ""

[sigfldz]
alias = "Z当前场"
U = "T"
numread = 1
optkeys = []
separator = ""
optvalues = []
help = ""
type = "read"
cmdheader = ""

[sigactnz]
alias = "Z状态"
U = ""
numread = 1
optkeys = ["HOLD", "RTOS", "RTOZ", "CLMP"]
separator = ""
optvalues = ["HOLD", "RTOS", "RTOZ", "CLMP"]
help = "HOLD:RTOS:RTOZ:CLMP      Ramp status (Hold, to set, to zero, clamp)"
type = "set"
cmdheader = ""

[drivey]
alias = "驱动Y"
U = "T"
numread = 1
optkeys = []
separator = ""
optvalues = []
help = ""
type = "set"
cmdheader = ""

[zheater]
alias = "Z加热器"
U = ""
numread = 1
optkeys = ["ON", "OFF"]
separator = ""
optvalues = ["ON", "OFF"]
help = ""
type = "set"
cmdheader = ""

[conf]
idn = "MERCURY IPS"
output_labels = ["X -", "Y -", "Z -"]
icon = ""
input_labels = ["X +", "Y +", "Z +"]
cmdtype = "scpi"

[sigfsety]
alias = "Y目标场"
U = "T"
numread = 1
optkeys = []
separator = ""
optvalues = []
help = ""
type = "set"
cmdheader = ""

[zheatertimespent]
alias = "Z加热器触发时间"
U = "s"
numread = 1
optkeys = []
separator = ""
optvalues = []
help = ""
type = "read"
cmdheader = ""
