[setflowctl]
cmdheader = ""
optkeys = ["Manual", "Auto"]
help = ""
timeoutw = 3
alias = "流量控制"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = ["OFF", "ON"]
type = "set"

[enablepid]
cmdheader = ""
optkeys = ["Manual", "Auto"]
help = ""
timeoutw = 3
alias = "PID开关"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = ["OFF", "ON"]
type = "set"

[angleread]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "读角度"
U = "°"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "read"

[setheater]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "设置加热器"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "set"

[setsweepmode]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "设置扫温模式"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "set"

[angleset]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "角度设置"
U = "°"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "set"

[settemp]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "设置温度"
U = "K"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "set"

[conf]
idn = "MERCURY ITC"
output_labels = []
icon = ""
input_labels = []
cmdtype = "scpi"

[temperature]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "温度"
U = "K"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "read"

[setflow]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "设置流量"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "set"
