[sigactny]
cmdheader = ""
optkeys = ["HOLD", "RTOS", "RTOZ", "CLMP"]
help = "HOLD:RTOS:RTOZ:CLMP      Ramp status (Hold, to set, to zero, clamp)"
timeoutw = 3
alias = "Y状态"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = ["HOLD", "RTOS", "RTOZ", "CLMP"]
type = "set"

[magnetT]
cmdheader = ""
optkeys = []
help = "magnet temperature"
timeoutw = 3
alias = "磁体温度"
U = "K"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "read"

[nitrogenlevel]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "N2液面"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "read"

[heliumlevel]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "He4液面"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "read"

[sigvoltz]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "Z电压"
U = "V"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "read"

[sigfldy]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "Y当前场"
U = "T"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "read"

[sigrfstz]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "Z扫描速率"
U = "T/min"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "set"

[sigfsetx]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "X目标场"
U = "T"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "set"

[sigfldx]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "X当前场"
U = "T"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "read"

[heliumlevelrmode]
cmdheader = ""
optkeys = ["Fast", "Slow"]
help = ""
timeoutw = 3
alias = "He4液面读取模式"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = ["OFF", "ON"]
type = "set"

[sigrfsty]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "Y扫描速率"
U = "T/min"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "set"

[drivez]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "驱动Z"
U = "T"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "set"

[sigcurrz]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "Z电流"
U = "A"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "read"

[drivex]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "驱动X"
U = "T"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "set"

[sigactnx]
cmdheader = ""
optkeys = ["HOLD", "RTOS", "RTOZ", "CLMP"]
help = "HOLD:RTOS:RTOZ:CLMP      Ramp status (Hold, to set, to zero, clamp)"
timeoutw = 3
alias = "X状态"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = ["HOLD", "RTOS", "RTOZ", "CLMP"]
type = "set"

[sigpfldy]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "Y当前恒定场"
U = "T"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "read"

[zheatertime]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "Z加热器时间"
U = "s"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "set"

[sigfsetz]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "Z目标场"
U = "T"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "set"

[sigrfstx]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "X扫描速率"
U = "T/min"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "set"

[sigpfldz]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "Z当前恒定场"
U = "T"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "read"

[sigpcurz]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "Z稳恒电流"
U = "A"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "read"

[sigpfldx]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "X当前恒定场"
U = "T"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "read"

[sigfldz]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "Z当前场"
U = "T"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "read"

[sigactnz]
cmdheader = ""
optkeys = ["HOLD", "RTOS", "RTOZ", "CLMP"]
help = "HOLD:RTOS:RTOZ:CLMP      Ramp status (Hold, to set, to zero, clamp)"
timeoutw = 3
alias = "Z状态"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = ["HOLD", "RTOS", "RTOZ", "CLMP"]
type = "set"

[drivey]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "驱动Y"
U = "T"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "set"

[zheater]
cmdheader = ""
optkeys = ["ON", "OFF"]
help = ""
timeoutw = 6
alias = "Z加热器"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = ["ON", "OFF"]
type = "set"

[conf]
idn = "MERCURY IPS"
output_labels = ["X -", "Y -", "Z -"]
icon = ""
input_labels = ["X +", "Y +", "Z +"]
cmdtype = "scpi"

[sigfsety]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "Y目标场"
U = "T"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "set"

[zheatertimespent]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "Z加热器触发时间"
U = "s"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "read"
