[fieldread]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "磁场读取"
U = "Oe"
timeoutr = 3.0
numread = 4
separator = ""
optvalues = []
type = "read"

[positionmode]
cmdheader = ""
optkeys = ["Move", "Cal Limit", "Cal Present"]
help = ""
timeoutw = 3
alias = "转角模式"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = ["0", "1", "2"]
type = "set"

[fieldrate]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "磁场速率"
U = "Oe/s"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "set"

[positionpos]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "角度设置"
U = "°"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "set"

[temperaturerate]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "温度速率"
U = "K/min"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "set"

[positionread]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "角度读取"
U = "°"
timeoutr = 3.0
numread = 4
separator = ""
optvalues = []
type = "read"

[temperature]
cmdheader = "TEMP"
optkeys = []
help = ""
timeoutw = 3
alias = "温度"
U = ""
timeoutr = 3.0
numread = 3
separator = ","
optvalues = []
type = "set"

[channel1]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "通道1"
U = "Ω"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "read"

[temperatureAC]
cmdheader = ""
optkeys = ["Fast Settle", "No Overshoot"]
help = ""
timeoutw = 3
alias = "温度接近方式"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = ["0", "1"]
type = "set"

[field]
cmdheader = "FIELD"
optkeys = []
help = ""
timeoutw = 3
alias = "磁场"
U = ""
timeoutr = 3.0
numread = 4
separator = ","
optvalues = []
type = "set"

[position]
cmdheader = "MOVE"
optkeys = []
help = ""
timeoutw = 3
alias = "角度"
U = ""
timeoutr = 3.0
numread = 3
separator = ","
optvalues = []
type = "set"

[channel2]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "通道2"
U = "Ω"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "read"

[fieldfield]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "磁场设置值"
U = "Oe"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "set"

[positionSDC]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "转角减速方式"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "set"

[channel3]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "通道3"
U = "Ω"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "read"

[tempread]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "温度读取"
U = "K"
timeoutr = 3.0
numread = 4
separator = ""
optvalues = []
type = "read"

[fieldMM]
cmdheader = ""
optkeys = ["Persistent", "Driven"]
help = ""
timeoutw = 3
alias = "磁场模式"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = ["0", "1"]
type = "set"

[fieldAM]
cmdheader = ""
optkeys = ["Linear", "No Overshoot", "Oscillate"]
help = ""
timeoutw = 3
alias = "磁场接近模式"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = ["0", "1", "2"]
type = "set"

[chamber]
cmdheader = "CHAMBER"
optkeys = ["Seal Immediately", "Purge and Seal", "Vent and Seal", "Pump Continuously", "Vent Continuously"]
help = ""
timeoutw = 3
alias = "腔体"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = ["0", "1", "2", "3", "4"]
type = "set"

[channel4]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "通道4"
U = "Ω"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "read"

[conf]
idn = "PPMS"
output_labels = []
icon = ""
input_labels = []
cmdtype = "scpi"

[temperaturetemp]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "温度设置"
U = "K"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "set"
