[drimixs]
alias = "混合室温度"
U = "K"
numread = 1
optkeys = []
separator = ""
optvalues = []
help = ""
type = "read"
cmdheader = ""

[drimixclheater]
alias = "混合室加热器"
U = ""
numread = 2
optkeys = []
separator = ","
optvalues = []
help = ""
type = "set"
cmdheader = ""

[conf]
idn = "Proteox"
output_labels = []
icon = ""
input_labels = []
cmdtype = ""

[claimcontrol]
alias = "控制声明"
U = ""
numread = 1
optkeys = ["claim control", "relinquich control"]
separator = ""
optvalues = ["1", "0"]
help = ""
type = "set"
cmdheader = ""
