[drimixs]
alias = "混合室温度"
U = "K"
numread = 1
optkeys = []
help = ""
optvalues = []
separator = ""
type = "read"
cmdheader = ""

[conf]
idn = "Proteox"
output_labels = []
icon = ""
input_labels = []
cmdtype = ""
