[drimixs]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "混合室温度"
U = "K"
timeoutr = 3.0
numread = 1
separator = ""
optvalues = []
type = "read"

[drimixclheater]
cmdheader = ""
optkeys = []
help = ""
timeoutw = 3
alias = "混合室加热器"
U = ""
timeoutr = 3.0
numread = 2
separator = ","
optvalues = []
type = "set"

[conf]
idn = "Proteox"
output_labels = []
icon = ""
input_labels = []
cmdtype = ""

[claimcontrol]
cmdheader = ""
optkeys = ["claim control", "relinquich control"]
help = ""
timeoutw = 3
alias = "控制声明"
U = ""
timeoutr = 3.0
numread = 1
separator = ""
optvalues = ["1", "0"]
type = "set"
