[apllf]
cmdheader = "AMPL"
optkeys = []
help = ""
timeoutw=0.3
alias = "低频功率"
U = "dBm"
timeoutr=3
numread = 1
separator = ""
optvalues = []
type = "sweep"

[enablehf]
cmdheader = "ENBH"
optkeys = ["Disabled", "Enabled"]
help = ""
timeoutw=0.3
alias = "启用高频"
U = ""
timeoutr=3
numread = 1
separator = ""
optvalues = ["0", "1"]
type = "set"

[enablelf]
cmdheader = "ENBL"
optkeys = ["Disabled", "Enabled"]
help = ""
timeoutw=0.3
alias = "启用低频"
U = ""
timeoutr=3
numread = 1
separator = ""
optvalues = ["0", "1"]
type = "set"

[aplrf]
cmdheader = "AMPR"
optkeys = []
help = ""
timeoutw=0.3
alias = "射频功率"
U = "dBm"
timeoutr=3
numread = 1
separator = ""
optvalues = []
type = "sweep"

[enablerf]
cmdheader = "ENBR"
optkeys = ["Disabled", "Enabled"]
help = ""
timeoutw=0.3
alias = "启用射频"
U = ""
timeoutr=3
numread = 1
separator = ""
optvalues = ["0", "1"]
type = "set"

[frequency]
cmdheader = "FREQ"
optkeys = []
help = ""
timeoutw=0.3
alias = "频率"
U = "Hz"
timeoutr=3
numread = 1
separator = ""
optvalues = []
type = "sweep"

[conf]
idn = "SG384"
output_labels = []
icon = ""
input_labels = []
cmdtype = "scpi"

[aplhf]
cmdheader = "AMPH"
optkeys = []
help = ""
timeoutw=0.3
alias = "高频功率"
U = "dBm"
timeoutr=3
numread = 1
separator = ""
optvalues = []
type = "sweep"
