[temperatureT3]
cmdheader = ""
U = "K"
enable = true
optkeys = []
help = "Still Plate"
optvalues = []
type = "read"
alias = "温度T3"

[temperatureT1]
cmdheader = ""
U = "K"
enable = true
optkeys = []
help = "PT2 Head"
optvalues = []
type = "read"
alias = "温度T1"

[temperatureT7]
cmdheader = ""
U = "K"
enable = true
optkeys = []
help = "PT1 Plate"
optvalues = []
type = "read"
alias = "温度T7"

[temperatureT5]
cmdheader = ""
U = "K"
enable = true
optkeys = []
help = "MC Plate Cernox"
optvalues = []
type = "read"
alias = "温度T5"

[temperatureT2]
cmdheader = ""
U = "K"
enable = true
optkeys = []
help = "PT2 Plate"
optvalues = []
type = "read"
alias = "温度T2"

[temperatureT4]
cmdheader = ""
U = "K"
enable = true
optkeys = []
help = "Cold Plate"
optvalues = []
type = "read"
alias = "温度T4"

[conf]
idn = "Triton"
output_labels = []
icon = ""
input_labels = []
cmdtype = "scpi"

[temperatureT8]
cmdheader = ""
U = "K"
enable = true
optkeys = []
help = "MC Plate RuO2"
optvalues = []
type = "read"
alias = "温度T8"

[temperatureT13]
cmdheader = ""
U = "K"
enable = true
optkeys = []
help = "Magnet"
optvalues = []
type = "read"
alias = "温度T13"

[temperatureT6]
cmdheader = ""
U = "K"
enable = true
optkeys = []
help = "PT1 Head"
optvalues = []
type = "read"
alias = "温度T6"
