[tlm400probebautotset]
alias = "TLM400样品杆B自动控温"
U = "K"
numread = 1
optkeys = []
separator = ""
optvalues = []
help = ""
type = "set"
cmdheader = ""

[tlm400probeautotsetsw]
alias = "TLM400样品杆自动控温开关"
U = ""
numread = 1
optkeys = ["ON", "OFF"]
separator = ""
optvalues = ["ON", "OFF"]
help = ""
type = "set"
cmdheader = ""

[temperatureT5]
alias = "温度T5"
U = "K"
numread = 1
optkeys = []
separator = ""
optvalues = []
help = "MC Plate Cernox"
type = "read"
cmdheader = ""

[temperatureT4]
alias = "温度T4"
U = "K"
numread = 1
optkeys = []
separator = ""
optvalues = []
help = "Cold Plate"
type = "read"
cmdheader = ""

[taloopP]
alias = "TAPID - P"
U = ""
numread = 1
optkeys = []
separator = ""
optvalues = []
help = ""
type = "set"
cmdheader = ""

[taloopI]
alias = "TAPID - I"
U = ""
numread = 1
optkeys = []
separator = ""
optvalues = []
help = ""
type = "set"
cmdheader = ""

[temperatureT1]
alias = "温度T1"
U = "K"
numread = 1
optkeys = []
separator = ""
optvalues = []
help = "PT2 Head"
type = "read"
cmdheader = ""

[h2power]
alias = "加热器H2功率"
U = "μW"
numread = 1
optkeys = []
separator = ""
optvalues = []
help = ""
type = "set"
cmdheader = ""

[taloopPID]
alias = "TAPID"
U = ""
numread = 1
optkeys = []
separator = ""
optvalues = []
help = ""
type = "set"
cmdheader = ""

[temperatureT6]
alias = "温度T6"
U = "K"
numread = 1
optkeys = []
separator = ""
optvalues = []
help = "PT1 Head"
type = "read"
cmdheader = ""

[temperatureT13]
alias = "温度T13"
U = "K"
numread = 1
optkeys = []
separator = ""
optvalues = []
help = "Magnet"
type = "read"
cmdheader = ""

[temperatureT3]
alias = "温度T3"
U = "K"
numread = 1
optkeys = []
separator = ""
optvalues = []
help = "Still Plate"
type = "read"
cmdheader = ""

[taexcitationcur]
alias = "TA激励电流"
U = "A"
numread = 1
optkeys = ["316pA", "1nA", "3.16nA", "10nA", "31.6nA", "100nA"]
separator = ""
optvalues = ["316pA", "1nA", "3.16nA", "10nA", "31.6nA", "100nA"]
help = ""
type = "set"
cmdheader = ""

[temperatureT7]
alias = "温度T7"
U = "K"
numread = 1
optkeys = []
separator = ""
optvalues = []
help = "PT1 Plate"
type = "read"
cmdheader = ""

[looptset]
alias = "温度设置"
U = "K"
numread = 1
optkeys = []
separator = ""
optvalues = []
help = ""
type = "set"
cmdheader = ""

[tlm400probeaautotset]
alias = "TLM400样品杆A自动控温"
U = "K"
numread = 1
optkeys = []
separator = ""
optvalues = []
help = ""
type = "set"
cmdheader = ""

[tlm400probecautotset]
alias = "TLM400样品杆C自动控温"
U = "K"
numread = 1
optkeys = []
separator = ""
optvalues = []
help = ""
type = "set"
cmdheader = ""

[temperatureT8]
alias = "温度T8"
U = "K"
numread = 1
optkeys = []
separator = ""
optvalues = []
help = "MC Plate RuO2"
type = "read"
cmdheader = ""

[taexcitationvolt]
alias = "TA激励电压"
U = "V"
numread = 1
optkeys = []
separator = ""
optvalues = []
help = ""
type = "set"
cmdheader = ""

[looprange]
alias = "加热器范围"
U = "mA"
numread = 1
optkeys = ["0", "31.6 μA", "100 μA", "316 μA", "1 mA", "3.16 mA", "10 mA", "31.6 mA", "100 mA"]
separator = ""
optvalues = ["0", "0.0316", "0.1", "0.316", "1", "3.16", "10", "31.6", "100"]
help = ""
type = "set"
cmdheader = ""

[temperatureTA]
alias = "温度TA"
U = "K"
numread = 1
optkeys = []
separator = ""
optvalues = []
help = ""
type = "read"
cmdheader = ""

[temperatureT2]
alias = "温度T2"
U = "K"
numread = 1
optkeys = []
separator = ""
optvalues = []
help = "PT2 Plate"
type = "read"
cmdheader = ""

[taloopD]
alias = "TAPID - D"
U = ""
numread = 1
optkeys = []
separator = ""
optvalues = []
help = ""
type = "set"
cmdheader = ""

[taexcitationtype]
alias = "TA激励类型"
U = ""
numread = 1
optkeys = ["电流", "电压"]
separator = ""
optvalues = ["CUR", "VOLT"]
help = ""
type = "set"
cmdheader = ""

[conf]
idn = "Triton"
output_labels = []
icon = ""
input_labels = []
cmdtype = "scpi"

[loopmode]
alias = "闭合PID"
U = ""
numread = 1
optkeys = ["ON", "OFF"]
separator = ""
optvalues = ["ON", "OFF"]
help = ""
type = "set"
cmdheader = ""
