[tlm400probebautotset]
cmdheader = ""
optkeys = []
help = ""
timeoutw=0.3
alias = "TLM400样品杆B自动控温"
U = "K"
timeoutr=3
numread = 1
separator = ""
optvalues = []
type = "set"

[t8autotsetsw]
cmdheader = ""
optkeys = ["ON", "OFF"]
help = ""
timeoutw=8
alias = "T8自动控温开关"
U = ""
timeoutr=3
numread = 1
separator = ""
optvalues = ["ON", "OFF"]
type = "set"

[tlm400probeautotsetsw]
cmdheader = ""
optkeys = ["ON", "OFF"]
help = ""
timeoutw=8
alias = "TLM400样品杆自动控温开关"
U = ""
timeoutr=3
numread = 1
separator = ""
optvalues = ["ON", "OFF"]
type = "set"

[temperatureT5]
cmdheader = ""
optkeys = []
help = "MC Plate Cernox"
timeoutw=0.3
alias = "温度T5"
U = "K"
timeoutr=3
numread = 1
separator = ""
optvalues = []
type = "read"

[temperatureT4]
cmdheader = ""
optkeys = []
help = "Cold Plate"
timeoutw=0.3
alias = "温度T4"
U = "K"
timeoutr=3
numread = 1
separator = ""
optvalues = []
type = "read"

[t8excitationtype]
cmdheader = ""
optkeys = ["电流", "电压"]
help = ""
timeoutw=0.3
alias = "T8激励类型"
U = ""
timeoutr=3
numread = 1
separator = ""
optvalues = ["CUR", "VOLT"]
type = "set"

[taloopP]
cmdheader = ""
optkeys = []
help = ""
timeoutw=0.3
alias = "TAPID - P"
U = ""
timeoutr=3
numread = 1
separator = ""
optvalues = []
type = "set"

[taloopI]
cmdheader = ""
optkeys = []
help = ""
timeoutw=0.3
alias = "TAPID - I"
U = ""
timeoutr=3
numread = 1
separator = ""
optvalues = []
type = "set"

[temperatureT1]
cmdheader = ""
optkeys = []
help = "PT2 Head"
timeoutw=0.3
alias = "温度T1"
U = "K"
timeoutr=3
numread = 1
separator = ""
optvalues = []
type = "read"

[h2power]
cmdheader = ""
optkeys = []
help = ""
timeoutw=0.3
alias = "加热器H2功率"
U = "μW"
timeoutr=3
numread = 1
separator = ""
optvalues = []
type = "set"

[taloopPID]
cmdheader = ""
optkeys = []
help = ""
timeoutw=0.3
alias = "TAPID"
U = ""
timeoutr=3
numread = 1
separator = ""
optvalues = []
type = "set"

[t8loopmode]
cmdheader = ""
optkeys = ["ON", "OFF"]
help = ""
timeoutw=8
alias = "T8闭合PID"
U = ""
timeoutr=3
numread = 1
separator = ""
optvalues = ["ON", "OFF"]
type = "set"

[temperatureT6]
cmdheader = ""
optkeys = []
help = "PT1 Head"
timeoutw=0.3
alias = "温度T6"
U = "K"
timeoutr=3
numread = 1
separator = ""
optvalues = []
type = "read"

[temperatureT13]
cmdheader = ""
optkeys = []
help = "Magnet"
timeoutw=0.3
alias = "温度T13"
U = "K"
timeoutr=3
numread = 1
separator = ""
optvalues = []
type = "read"

[t8loopD]
cmdheader = ""
optkeys = []
help = ""
timeoutw=0.3
alias = "T8PID - D"
U = ""
timeoutr=3
numread = 1
separator = ""
optvalues = []
type = "set"

[temperatureT3]
cmdheader = ""
optkeys = []
help = "Still Plate"
timeoutw=0.3
alias = "温度T3"
U = "K"
timeoutr=3
numread = 1
separator = ""
optvalues = []
type = "read"

[taexcitationcur]
cmdheader = ""
optkeys = ["316pA", "1nA", "3.16nA", "10nA", "31.6nA", "100nA"]
help = ""
timeoutw=0.3
alias = "TA激励电流"
U = "A"
timeoutr=3
numread = 1
separator = ""
optvalues = ["316pA", "1nA", "3.16nA", "10nA", "31.6nA", "100nA"]
type = "set"

[t8loopP]
cmdheader = ""
optkeys = []
help = ""
timeoutw=0.3
alias = "T8PID - P"
U = ""
timeoutr=3
numread = 1
separator = ""
optvalues = []
type = "set"

[talooprange]
cmdheader = ""
optkeys = ["0", "31.6 μA", "100 μA", "316 μA", "1 mA", "3.16 mA", "10 mA", "31.6 mA", "100 mA"]
help = ""
timeoutw=0.3
alias = "TA加热器范围"
U = "mA"
timeoutr=3
numread = 1
separator = ""
optvalues = ["0", "0.0316", "0.1", "0.316", "1", "3.16", "10", "31.6", "100"]
type = "set"

[t8excitationvolt]
cmdheader = ""
optkeys = ["2μV", "6.32μV", "20μV", "63.2μV", "200μV", "632μV", "2mV", "6.32mV", "20mV", "63.2mV", "200mV", "632mV"]
help = ""
timeoutw=0.3
alias = "T8激励电压"
U = "V"
timeoutr=3
numread = 1
separator = ""
optvalues = ["0.000002", "0.00000632", "0.00002", "0.0000632", "0.0002", "0.000632", "0.002", "0.00632", "0.02", "0.0632", "0.2", "0.632"]
type = "set"

[temperatureT7]
cmdheader = ""
optkeys = []
help = "PT1 Plate"
timeoutw=0.3
alias = "温度T7"
U = "K"
timeoutr=3
numread = 1
separator = ""
optvalues = []
type = "read"

[tlm400probeaautotset]
cmdheader = ""
optkeys = []
help = ""
timeoutw=0.3
alias = "TLM400样品杆A自动控温"
U = "K"
timeoutr=3
numread = 1
separator = ""
optvalues = []
type = "set"

[t8looprange]
cmdheader = ""
optkeys = ["0", "31.6 μA", "100 μA", "316 μA", "1 mA", "3.16 mA", "10 mA", "31.6 mA", "100 mA"]
help = ""
timeoutw=0.3
alias = "T8加热器范围"
U = "mA"
timeoutr=3
numread = 1
separator = ""
optvalues = ["0", "0.0316", "0.1", "0.316", "1", "3.16", "10", "31.6", "100"]
type = "set"

[t8excitationcur]
cmdheader = ""
optkeys = ["316pA", "1nA", "3.16nA", "10nA", "31.6nA", "100nA"]
help = ""
timeoutw=0.3
alias = "T8激励电流"
U = "A"
timeoutr=3
numread = 1
separator = ""
optvalues = ["316pA", "1nA", "3.16nA", "10nA", "31.6nA", "100nA"]
type = "set"

[tlm400probecautotset]
cmdheader = ""
optkeys = []
help = ""
timeoutw=0.3
alias = "TLM400样品杆C自动控温"
U = "K"
timeoutr=3
numread = 1
separator = ""
optvalues = []
type = "set"

[temperatureT8]
cmdheader = ""
optkeys = []
help = "MC Plate RuO2"
timeoutw=0.3
alias = "温度T8"
U = "K"
timeoutr=3
numread = 1
separator = ""
optvalues = []
type = "read"

[taexcitationvolt]
cmdheader = ""
optkeys = []
help = ""
timeoutw=0.3
alias = "TA激励电压"
U = "V"
timeoutr=3
numread = 1
separator = ""
optvalues = []
type = "set"

[t8loopI]
cmdheader = ""
optkeys = []
help = ""
timeoutw=0.3
alias = "T8PID - I"
U = ""
timeoutr=3
numread = 1
separator = ""
optvalues = []
type = "set"

[temperatureTA]
cmdheader = ""
optkeys = []
help = ""
timeoutw=0.3
alias = "温度TA"
U = "K"
timeoutr=3
numread = 1
separator = ""
optvalues = []
type = "read"

[talooptset]
cmdheader = ""
optkeys = []
help = ""
timeoutw=0.3
alias = "TA温度设置"
U = "K"
timeoutr=3
numread = 1
separator = ""
optvalues = []
type = "set"

[t8loopPID]
cmdheader = ""
optkeys = []
help = ""
timeoutw=0.3
alias = "T8PID"
U = ""
timeoutr=3
numread = 1
separator = ""
optvalues = []
type = "set"

[taloopmode]
cmdheader = ""
optkeys = ["ON", "OFF"]
help = ""
timeoutw=8
alias = "TA闭合PID"
U = ""
timeoutr=3
numread = 1
separator = ""
optvalues = ["ON", "OFF"]
type = "set"

[t8autotset]
cmdheader = ""
optkeys = []
help = ""
timeoutw=0.3
alias = "T8自动控温"
U = "K"
timeoutr=3
numread = 1
separator = ""
optvalues = []
type = "set"

[temperatureT2]
cmdheader = ""
optkeys = []
help = "PT2 Plate"
timeoutw=0.3
alias = "温度T2"
U = "K"
timeoutr=3
numread = 1
separator = ""
optvalues = []
type = "read"

[taloopD]
cmdheader = ""
optkeys = []
help = ""
timeoutw=0.3
alias = "TAPID - D"
U = ""
timeoutr=3
numread = 1
separator = ""
optvalues = []
type = "set"

[taexcitationtype]
cmdheader = ""
optkeys = ["电流", "电压"]
help = ""
timeoutw=0.3
alias = "TA激励类型"
U = ""
timeoutr=3
numread = 1
separator = ""
optvalues = ["CUR", "VOLT"]
type = "set"

[t8looptset]
cmdheader = ""
optkeys = []
help = ""
timeoutw=0.3
alias = "T8温度设置"
U = "K"
timeoutr=3
numread = 1
separator = ""
optvalues = []
type = "set"

[conf]
idn = "Triton"
output_labels = []
icon = ""
input_labels = []
cmdtype = "scpi"
