[Date]
alias = "日期"
U = ""
numread = 1
optkeys = []
separator = ""
optvalues = []
help = "Return a Date corresponding to the user's system time including the system timezone locale."
type = "read"
cmdheader = ""

[YearMonthDayHMSM]
alias = "年月日时分秒毫秒"
U = ""
numread = 7
optkeys = []
separator = ","
optvalues = []
help = "Return a DateTime corresponding to the user's system time including the system timezone locale."
type = "read"
cmdheader = ""

[Vac]
alias = "JJ Vac"
U = "V"
numread = 1
optkeys = []
separator = ""
optvalues = []
help = "仅作为测试"
type = "read"
cmdheader = ""

[B]
alias = "JJ B"
U = "T"
numread = 1
optkeys = []
separator = ""
optvalues = []
help = "仅作为测试"
type = "sweep"
cmdheader = ""

[Time]
alias = "时间"
U = ""
numread = 1
optkeys = []
separator = ""
optvalues = []
help = "Return a Time corresponding to the user's system time including the system timezone locale."
type = "read"
cmdheader = ""

[SystemTime]
alias = "系统时间"
U = "s"
numread = 1
optkeys = []
separator = ""
optvalues = []
help = "Get the system time in seconds since the epoch, with fairly high (typically, microsecond) resolution."
type = "read"
cmdheader = ""

[power]
alias = "Power"
U = ""
numread = 1
optkeys = ["ON", "OFF"]
separator = ""
optvalues = ["1", "0"]
help = "仅作为设置测试"
type = "set"
cmdheader = ""

[Iac]
alias = "JJ Iac"
U = "A"
numread = 1
optkeys = []
separator = ""
optvalues = []
help = "仅作为测试"
type = "sweep"
cmdheader = ""

[DateTime]
alias = "日期和时间"
U = ""
numread = 1
optkeys = []
separator = ""
optvalues = []
help = "Return a DateTime corresponding to the user's system time including the system timezone locale."
type = "read"
cmdheader = ""

[Vacrange]
alias = "JJ Vac Range"
U = "V"
numread = 1
optkeys = ["1V", "1mV", "1μV"]
separator = ""
optvalues = ["1", "1e-3", "1e-6"]
help = "仅作为测试"
type = "set"
cmdheader = ""

[VacCtrl]
alias = "JJ Vac Ctrl"
U = "V"
numread = 4
optkeys = []
separator = ","
optvalues = []
help = "仅作为测试"
type = "read"
cmdheader = ""

[I]
alias = "JJ I"
U = "A"
numread = 1
optkeys = []
separator = ""
optvalues = []
help = "仅作为测试"
type = "sweep"
cmdheader = ""

[conf]
idn = "VirtualInstr"
output_labels = []
icon = ""
input_labels = []
cmdtype = ""
