[B]
alias = "JJ B"
U = "T"
optkeys = []
help = "仅作为测试"
optvalues = []
type = "sweep"
cmdheader = ""

[SystemTime]
alias = "系统时间"
U = "s"
optkeys = []
help = "Get the system time in seconds since the epoch, with fairly high (typically, microsecond) resolution."
optvalues = []
type = "read"
cmdheader = ""

[I]
alias = "JJ I"
U = "A"
optkeys = []
help = "仅作为测试"
optvalues = []
type = "sweep"
cmdheader = ""

[Date]
alias = "日期"
U = ""
optkeys = []
help = "Return a Date corresponding to the user's system time including the system timezone locale."
optvalues = []
type = "read"
cmdheader = ""

[Time]
alias = "时间"
U = ""
optkeys = []
help = "Return a Time corresponding to the user's system time including the system timezone locale."
optvalues = []
type = "read"
cmdheader = ""

[power]
alias = "Power"
U = ""
optkeys = ["ON", "OFF"]
help = "仅作为设置测试"
optvalues = ["1", "0"]
type = "set"
cmdheader = ""

[conf]
idn = "VirtualInstr"
output_labels = []
icon = ""
input_labels = []
cmdtype = ""

[Vac]
alias = "JJ Vac"
U = "V"
optkeys = []
help = "仅作为测试"
optvalues = []
type = "read"
cmdheader = ""

[Iac]
alias = "JJ Iac"
U = "A"
optkeys = []
help = "仅作为测试"
optvalues = []
type = "sweep"
cmdheader = ""

[DateTime]
alias = "日期和时间"
U = ""
optkeys = []
help = "Return a DateTime corresponding to the user's system time including the system timezone locale."
optvalues = []
type = "read"
cmdheader = ""
