[Basic]
isremote = true
remoteprocessdata = false
viewportenable = true
scale = false
hidewindow = false
nthreads = 1
windowsize = [1280, 720]
encoding = "GBK"
editor = "notepad"
language = "简体中文"

    [Basic.languages]
    English = "D:\\UserData\\XuLei\\QInsControl.jl\\../QInsControlAssets\\Languages\\English.toml"
    "简体中文" = "D:\\UserData\\XuLei\\QInsControl.jl\\../QInsControlAssets\\Languages\\SimplifiedChinese.toml"

[DtViewer]
showdatarow = 10000

[DAQ]
saveimg = false
logall = false
equalstep = true
showeditplotlayout = true
freelayout = true
savetime = 60
channel_size = 512
packsize = 6
plotshowcol = 2
pick_fps = [3, 36]
historylen = 120
retrysendtimes = 3
retryconnecttimes = 3

[InsBuf]
showhelp = false
showcol = 3
refreshrate = 1.0

    [InsBuf.disablelist.Triton]
    "TCPIP::192.168.0.2::33576::SOCKET" = ["taexcitationvolt", "taexcitationtype", "loopmode", "taloopD", "looptset", "taloopI", "looprange", "taexcitationcur", "hrtlm400tapbautotset", "hrtlm400tapbautotsetsw", "taloopP", "taloopPID", "temperatureTA"]

    [InsBuf.unitlist.K2612."GPIB1::17::INSTR"]
    Bmeasurerangei = 4
    Bmeasurei = 4
    Bsourcelimiti = 4
    Bsourcerangei = 4

    [InsBuf.unitlist.LI5650."GPIB1::2::INSTR"]
    sensitivityvpPSD = 3

    [InsBuf.unitlist.LI5650."GPIB1::1::INSTR"]
    sensitivityipPSD = 4

    [InsBuf.unitlist.K2400."GPIB1::19::INSTR"]
    measureproti = 1

[Fonts]
dir = "D:\\UserData\\XuLei\\QInsControlAssets\\Fonts"
size = 18
plotfontsize = 30
first = "ZaoZiGongFangShangHeiG0v1ChangGuiTi-1.otf"
second = "arial.ttf"
plotfont = "arial.ttf"

[Console]
dir = "D:\\UserData\\XuLei\\QInsControlAssets\\IOs"
refreshrate = 60.0
showioline = 100
historylen = 120

[Logs]
dir = "D:\\UserData\\XuLei\\QInsControlAssets\\Logs"
refreshrate = 60.0
showlogline = 600
showloglength = 1000

[BGImage]
path = "C:\\Users\\ji66765\\Pictures\\Saved Pictures\\artwork-digital-art-stars-trees-nature-night-2191501-wallhere.com(1)(1).png"
useall = true

[ComAddr]
addrs = ["TCPIP::192.168.0.2::33576::SOCKET", "GPIB1::1::INSTR", "GPIB1::2::INSTR", "GPIB1::17::INSTR", "GPIB1::18::INSTR", "GPIB1::19::INSTR", "ASRL3::INSTR"]

[Style]
dir = "D:\\UserData\\XuLei\\QInsControl.jl\\../QInsControlAssets\\Styles"
default = "Dark"

[U]
T = ["T", "mT", "Gauss"]
V = ["V", "mV", "μV", "nV"]
mA = ["mA"]
Hz = ["Hz", "kHz", "MHz", "GHz"]
"T/min" = ["T minute^-1"]
s = ["s", "minute", "hr", "d", "ms", "μs"]
A = ["A", "mA", "μA", "nA"]
"μW" = ["μW"]
dBm = ["dBm"]
"°" = ["°", "rad"]
"" = [""]
K = ["K", "mK"]
"Ω" = ["Ω", "kΩ", "MΩ"]
