__language_name = "简体中文"
"No data input or incorrect input data!!!" = "没有数据输入或输入数据有误！！！"
"Edit Task" = "编辑任务"
Connected = "已连接"
Unconnected = "未连接"
SettingBlock = "设置模块"
variable = "变量"
Null = "空"
step = "步长"
General = "通用"
"window size" = "窗口大小"
variables = "变量"
Send = "发送"
"channel size" = "通道大小"
"No correct X input" = "X输入有误"
"No correct Y input" = "Y输入有误"
language = "语言"
Clear = "清除"
"Run All" = "全部运行"
address = "地址"
Switch = "切换"
Run = "运行"
Hold = "固定"
Drag = "拖拽"
"equal step sampling" = "等长采点"
"fixed step sampling" = "定长采点"
"Common Address" = "常用地址"
Script = "脚本"
alias = "别称"
text = "文本"
Close = "关闭"
"path does not exist!!!" = "路径不存在！！！"
"Filter aliases" = "筛选别称"
"Filter variables" = "筛选变量"
interface = "接口"
"identification string" = "身份字符"
"data tip" = "数据提示"
"Open Files" = "打开文件"
"log enabled quantities" = "记录启用变量"
"log all quantities" = "记录全部变量"
"Auto Search" = "自动查找"
title = "标题"
View = "查看"
"saving time" = "保存时间"
"font size" = "字体大小"
"Instrument Registration" = "仪器注册"
layout = "布局"
"data processing" = "数据处理"
size = "大小"
Resistance = "电阻"
read = "读取"
Edit = "编辑"
WriteBlock = "写入模块"
About = "关于"
Instrument = "仪器"
Disable = "停用"
Enable = "启用"
Stop = "停止"
Rename = "重命名"
content = "内容"
"data not loaded or data format not supported!" = "数据未加载或数据格式不支持！"
"Basic Setup" = "基本设置"
instrument = "仪器"
"Show Disabled" = "显示停用"
"Hide Disabled" = "隐藏停用"
"Delete Disabled" = "删除停用"
"insert above" = "上方插入"
"Data Selecting" = "数据选择"
pin = "阵脚"
Console = "控制台"
"icon size" = "图标大小"
"Task Queue" = "任务队列"
path = "路径"
QueryBlock = "询问模块"
font = "字体"
Workplace = "工作区"
"screenshot save" = "截图保存"
"Instrument CPU Monitor" = "仪器CPU监测"
Plot = "绘图"
Add = "添加"
"Insert Inside" = "内部插入"
Logger = "日志"
Variables = "变量"
"Confirm" = "确认"
Data = "数据"
Buffer = "缓存"
Circuit = "电路"
Controller = "控制器"
Controllers = "控制器"
ReadBlock = "读取模块"
Opened = "已打开"
Reboot = "重启"
CodeBlock = "代码模块"
"Load Project" = "加载项目"
Continue = "继续"
Interrupt = "中断"
"unit type" = "单位类型"
"insert below" = "下方插入"
Plots = "绘图"
"real-time data update/manual data update" = "实时数据更新/手动数据更新"
index = "索引"
"instrument address" = "仪器地址"
Delete = "删除"
Write = "写入"
Cancel = "取消"
command = "命令"
Status = "状态"
"set value" = "设置值"
"Refresh instrument list" = "刷新仪器列表"
Refresh = "刷新"
"display lines" = "显示行数"
Metrics = "监测"
"dual core" = "双核"
"single core" = "单核"
File = "文件"
Trilink = "三通"
"history command" = "历史命令"
"data amount per page" = "单页数据量"
Update = "更新"
"Insert Below" = "下方插入"
"plot type" = "绘图类型"
Copy = "复制"
"Edit queue: Task" = "编辑队列：任务"
"select data" = "选择数据"
"flip vertically" = "上下翻转"
Task = "任务"
Pin = "阵脚"
delay = "延迟"
"show help" = "显示帮助"
set = "设置"
Load = "加载"
output = "输出"
"matrix dimension" = "矩阵维度"
Filter = "筛选"
"Experimental Records" = "实验记录"
"display columns" = "显示列数"
"Display Columns" = "显示列数"
SaveBlock = "保存模块"
"Add Right" = "向右添加"
ReadingBlock = "读数模块"
"Data Browse" = "数据浏览"
"variable name" = "变量名"
stop = "终点"
"variable type" = "变量类型"
offset = "偏移"
" Stop " = " 结束 "
"Select Data" = "选择数据"
"Manual Input" = "手动输入"
"Ground End" = "接地头"
"code header" = "代码块头"
"Open Folder" = "打开文件夹"
version = "版本"
"Command Test" = "命令测试"
"multi-viewport mode off" = "多视窗模式 关"
"multi-viewport mode on" = "多视窗模式 开"
Save = "保存"
Annotation = "标注"
enable = "启用"
disable = "停用"
color = "颜色"
Query = "询问"
position = "位置"
refresh = "刷新"
"file does not exist!!!" = "文件不存在！！！"
"Add Left" = "向左添加"
StrideCodeBlock = "跨步代码模块"
Pause = "暂停"
"convert to" = "转换为"
"successfully started!" = "启动成功！"
type = "类型"
delete = "删除"
"refresh rate" = "刷新率"
"Convert to" = "转换为"
"Insert Above" = "上方插入"
"text editor" = "文本编辑器"
author = "作者"
"command type" = "命令类型"
"Universal Node" = "通用节点"
"packing size" = "打包尺寸"
New = "新建"
input = "输入"
Running = "运行中"
Icon = "图标"
"no workplace selected!!!" = "未选择工作区！！！"
Read = "读取"
mark = "标注"
Stopped = "已停止"
"Start" = "开始"
SweepBlock = "扫描模块"
FreeSweepBlock = "自由扫描模块"
Help = "帮助"
"Data Viewer" = "数据查看"
"Save Project" = "保存项目"
"flip horizontally" = "左右翻转"
Select = "选择"
"plot columns" = "绘图列数"
Samplebase = "样品座"
"Fast Mode" = "快速模式"
"Slow Mode" = "慢速模式"
"system encoding" = "系统编码"
Unit = "单位"
"Save Image" = "保存图像"
icon = "图标"
"optional values" = "可选值"
"Data Acquiring" = "数据采集"
sweep = "扫描"
Others = "其它"
Overview = "总览"
Preferences = "首选项"
Font = "字体"
number = "数字"
Style = "风格"
"sampling rate" = "采样率"
LogBlock = "记录模块"
"Confirm delete?" = "确认删除？"
Basic = "基本"
"Search Instruments" = "查找仪器"
"help document" = "帮助文档"
"unit set" = "单位集"
unit = "单位"
"Instrument Status" = "仪器状态"
label = "标签"
"instrument communication failed!!!" = "仪器通讯错误！！！"
"auto searching failed!!!" = "自动查找失败！！！"
"successfully added!" = "添加成功！"
"addition failed!!!" = "添加失败！！！"
"searching instruments" = "正在查找仪器"
"data acquiring or sweeping, please wait......" = "数据采集或扫描中，请稍等。。。"
"unavailable options!" = "不可用的选项！"
"Export" = "导出"
"instrument logging error, program terminates!!!" = "仪器记录错误，程序终止！！！"
BranchBlock = "分支模块"
"interpreting blocks failed!!!" = "模块解释错误！！！"
Interpret = "解释"
"pause!" = "暂停！"
"continue!" = "继续！"
"interrupt!" = "中断！"
"code branch" = "代码分支"
"scale on" = "缩放 开"
"scale off" = "缩放 关"
"nonuniform axes" = "非均匀坐标"
Paste = "粘贴"
"history blocks" = "历史模块"
Undo = "撤销"
Redo = "重做"
"hide window" = "隐藏窗口"
"Manual Refresh" = "手动刷新"
"Auto Refresh" = "自动刷新"
"Description" = "描述"
"Revision" = "修正"
"hide plot toolbar" = "隐藏绘图工具栏"
"show plot toolbar" = "显示绘图工具栏"
"Free layout" = "自由布局"
"New Plot" = "新绘图"
"threads" = "线程数"
"Updating..." = "更新中..."
"plot font" = "绘图字体"
"plot font size" = "绘图字体大小"
"Link to" = "链接到"
"Aux Dims" = "附加维"
"display length" = "显示长度"
"Copy Options" = "复制选项"
"Paste Options" = "粘贴选项"
"Paste Colors" = "粘贴颜色"
"Paste Variables" = "粘贴变量"
"Add Before" = "向前添加"
"Add After" = "向后添加"
"Add Group Before" = "向前添加组"
"Add Group After" = "向后添加组"
"Split Group" = "分割组"
"Sweep Quantity" = "扫描量"
"Set Quantity" = "设置量"
"Read Quantity" = "读取量"
"Global Options" = "全局选项"
"Variable Options" = "变量选项"
"Binding Options" = "绑定选项"
"SameLine Options" = "同行选项"
"Color Options" = "颜色选项"
"SameLine" = "同行"
"Text" = "文本"
"Configurations" = "配置"
"Widget" = "控件"
"Panel" = "面板"
"Image" = "图像"
"times of retrying sending commands" = "重试发令次数"
"times of retrying connecting" = "重试连接次数"
"Selector Type" = "选择器类型"
"Selector" = "选择器"
"Selector Options" = "选择器选项"
"Horizontal Linecut" = "水平截线"
"Vertical Linecut" = "竖直截线"
"Add Linecut" = "添加截线"
"FeedbackBlock" = "反馈模块"
"Instruments" = "仪器"
"Universal" = "通用"
"Ground" = "接地"
"Trilink21" = "三通21"
"Trilink12" = "三通12"
"SampleHolder" = "样品座"
"Sample Holder" = "样品座"
"Basic Nodes" = "基本节点"
"Instrument Nodes" = "仪器节点"
"segments" = "线段"
"DAQ threads" = "采数线程"
"Series" = "系列"
"legend" = "标签"
"axis" = "坐标系"
"matrix size" = "矩阵大小"
"nonuniform" = "非均匀"
"sampling" = "采样"
"sampling threshold" = "采样阈值"
"Options" = "选项"
"Widgets" = "控件"
"Show Serial Numbers" = "显示序号"
"Dragging Mode" = "拖拽模式"
"swap" = "交换"
"before" = "向前插入"
"after" = "向后插入"
"Merge Group Before" = "向前并组"
"Merge Group After" = "向后并组"
"Image Options" = "图像选项"
"New Task" = "新任务"
"No data!" = "无数据！"
"Common" = "通用"
"Open Formatter" = "打开格式器"
"Formatter" = "格式器"
"Data Formatter" = "数据格式器"
"Data Group" = "数据组"
"Codes" = "代码"
"Actions" = "动作"
"No actions!" = "无动作！"
"B\ne\nf\no\nr\ne" = "触\n \n发\n \n前"
"A\nf\nt\ne\nr" = "触\n \n发\n \n后"
"Communication" = "通信"
"visa path" = "VISA路径"
"stored data type" = "存储数据类型"
"Shape" = "形状"
"Draggable" = "拖拽"
"Show Positions" = "显示坐标"
"Position" = "坐标"
"Use Wallpaper" = "使用壁纸"
"Window Size" = "窗口大小"
"UI type" = "UI类型"
"Allow Overlap" = "允许重叠"
"Use Image" = "使用图像"
"Text Size" = "文本大小"
"Text Scale" = "文本缩放"
"Item Size" = "对象大小"
"Cursor Position" = "光标位置"
"Frame Rounding" = "区域圆角"
"Grab Rounding" = "抓手圆角"
"Border Rounding" = "边框圆角"
"Border Thickness" = "边框宽度"
"Binding Numbers" = "绑定数量"
"Binding to Widgets" = "控件绑定"
"Binding Index to RadioButton" = "单选索引绑定"
"Binding Index to ON/OFF" = "ON/OFF索引绑定"
"Window" = "窗口"
"Background" = "背景"
"Border" = "边框"
"Hovered" = "悬停"
"Activated" = "激活"
"Hint Text" = "提示文本"
"Combo Button" = "组合键"
"Popup Background" = "弹出框背景"
"Image Background" = "图像背景"
"Image Tint" = "图像色温"
"Toggle-on" = "开关-开"
"Toggle-off" = "开关-关"
"SliderGrab" = "抓手"
"Active SliderGrab" = "激活抓手"
"option" = "选项"
"No ArrowButton" = "无箭头"
"Text Inside" = "文本在里"
"Vertex" = "顶点"
"from" = "相对"
"Position Offset" = "位置偏移"
"Size Offset" = "尺寸偏移"
"Background Tint" = "背景色温"
"Wallpaper" = "壁纸"
"license" = "许可"
"Files" = "文件"
"Folders" = "文件夹"
"Formatters" = "格式器"
"Instrument Control" = "仪器控制"
"Widget Name" = "控件名称"
"Axis Scale" = "坐标刻度"
Colormap = "色谱"
"Segments" = "线段"
Ticks = "刻度"
Checked = "选中"
Indicator = "指针"
Base = "底座"
Linecuts = "截线"
"Horizontal Linecuts" = "水平截线"
"Vertical Linecuts" = "竖直截线"
"history widgets" = "历史控件"
"No Titlebar" = "无标题"
"No Resizing" = "无拉伸"
"No Collapsing" = "无折叠"
"No Docking" = "无拼接"
Spacing = "间距"
"Auto Spacing" = "自动分隔"
"Horizontal" = "水平"
Vertical = "竖直"
Left = "左"
Right = "右"
Top = "上"
Bottom = "下"
"Auto Align" = "自动对齐"
Path = "路径"
"Frame Padding" = "区域间距"
"Rate" = "速率"
"file-cutting length" = "文件切割长度"
"eval in Main" = "在Main中执行"
"eval in QInsControl" = "在QInsControl中执行"
separator = "分隔符"
Drivers = "驱动"
"No Times" = "无次数"
"No Time" = "无时间"
Set = "设置"
"Reading Index" = "读数索引"
"Add to" = "添加到"
Well = "良好"
Failed = "异常"
Processor = "处理器"
"controller buffer size" = "控制器缓冲区大小"
"controller timeout" = "控制器超时"
Unrecorded = "未记录"
": " = "："
Asynchronous = "异步"
Synchronous = "同步"
"Clear History" = "清除历史"
Settings = "设置"
"Communication Test" = "通信测试"
"Baud Rate" = "波特率"
Mode = "模式"
"Data Bits" = "数据位"
Parity = "奇偶校验"
"Stop Bits" = "停止位"
"Ready to Send" = "准备发送"
"Clear to Send" = "准备接收"
"Data Terminal Ready" = "数据终端就绪"
"Data Set Ready" = "数据设置就绪"
"Write Timeout" = "写入超时"
"Read Timeout" = "读取超时"
"Query Timeout" = "查询超时"
"Query Delay" = "查询延时"
"Termination Character" = "终止字符"
Title = "标题"
"Active Title" = "激活标题"
"Collapsed Title" = "折叠标题"
"Main Window" = "主窗口"
"hold main window" = "保持主窗口"
"no action swap interval" = "无动作交换间隔"
"duration" = "间隔"
"Log Out" = "登出"